// Render-edge i18n catalog for the content-type-inputs registry (en).
// AUTOGENERATED — source of truth: src/features/campaigns/lib/content-type-inputs.ts (English strings).
// Keyed on the registry's stable field `key` (+ per-type overrides where the same key
// carries a different English string). Do not hand-edit; regenerate from the registry.
const ns = {
  "categories": {
    "conversion-hook": "Conversion Hook",
    "authority-frame": "Authority Frame",
    "narrative-anchor": "Narrative Anchor",
    "structure-skeleton": "Structure Skeleton",
    "seo": "SEO & Keywords",
    "content-style": "Content Style",
    "engagement": "Engagement",
    "campaign-details": "Campaign Details",
    "format-specs": "Format & Specs",
    "audience": "Audience",
    "references": "References & Sources",
    "creative-direction": "Creative Direction"
  },
  "tone": {
    "professional": "Professional",
    "casual": "Casual",
    "inspirational": "Inspirational",
    "educational": "Educational",
    "humorous": "Humorous",
    "authoritative": "Authoritative",
    "conversational": "Conversational",
    "analytical": "Analytical",
    "journalistic": "Journalistic",
    "consultative": "Consultative",
    "direct": "Direct",
    "premium": "Premium",
    "friendly": "Friendly",
    "neutral-journalistic": "Neutral / Journalistic",
    "official": "Official",
    "warm-personal": "Warm / Personal",
    "advocacy": "Advocacy",
    "urgent": "Urgent",
    "playful": "Playful",
    "bold": "Bold",
    "aspirational": "Aspirational",
    "energetic": "Energetic",
    "cinematic": "Cinematic"
  },
  "cta": {
    "Direct": "Direct ask",
    "Question": "Question to engage",
    "Soft suggestion": "Soft suggestion",
    "Request a demo": "Request a demo",
    "Book a meeting": "Book a meeting",
    "Start free trial": "Start free trial",
    "Contact sales": "Contact sales"
  },
  "fields": {
    "uniqueAngle": {
      "label": "Unique Angle",
      "placeholder": "e.g. \"Most positioning frameworks fail because they treat positioning as creative rather than operational\"",
      "help": "What this content says that 95% of others don't — 1-2 sentences"
    },
    "evidencePieces": {
      "label": "Evidence Pieces",
      "placeholder": "One piece of evidence per line:\n- Reichheld churn data 2024\n- Patagonia case (Worn Wear)\n- Own voice-fidelity benchmark (n=200)",
      "help": "One piece of evidence per line — minimum 3, maximum 7 (quotes, statistics, customer examples, anecdotes)"
    },
    "counterClaim": {
      "label": "Counter-Claim (optional)",
      "placeholder": "e.g. \"Positioning is a constraint engineering problem, not a creative exercise\"",
      "help": "The anti-thesis the content explicitly refutes — sharpens the argument"
    },
    "articleStructure": {
      "label": "Article Structure",
      "help": "How the article is structured"
    },
    "includeFaq": {
      "label": "Include FAQ Section",
      "help": "Generate a FAQ block at the end — useful for SEO"
    },
    "seoKeyword": {
      "label": "SEO Keyword",
      "placeholder": "e.g. brand positioning strategy",
      "help": "Primary keyword to target for search ranking"
    },
    "secondaryKeywords": {
      "label": "Secondary Keywords",
      "placeholder": "Add keyword…",
      "help": "Related keywords to naturally incorporate"
    },
    "metaDescription": {
      "label": "Meta Description",
      "placeholder": "150-160 character SEO meta description",
      "help": "Search engine result snippet"
    },
    "internalLinks": {
      "label": "Internal Links to Include",
      "placeholder": "Add page/topic to link to…",
      "help": "Pages or topics to cross-reference"
    },
    "optimizationGoals": {
      "label": "Optimalisatiedoel",
      "help": "SEO draait de zoekmachine-pipeline; GEO genereert een citeerbaar artikel voor AI-antwoordmachines. Uitvinken slaat dat doel over."
    },
    "structure": {
      "label": "Structure"
    },
    "quoteCount": {
      "label": "Embedded Quotes (0–4)",
      "placeholder": "2",
      "help": "Number of quote placeholders to generate"
    },
    "includeBoilerplate": {
      "label": "Include Boilerplate",
      "help": "Standard \"About [Brand]\" block at the end"
    },
    "includeContactBlock": {
      "label": "Include Press Contact",
      "help": "Name / email / phone placeholders for media"
    },
    "jobTitle": {
      "label": "Job Title",
      "placeholder": "e.g. Senior Brand Strategist",
      "help": "Position title"
    },
    "jobLocation": {
      "label": "Location",
      "placeholder": "e.g. Amsterdam, Netherlands (Hybrid)",
      "help": "Work location and remote policy"
    },
    "salaryRange": {
      "label": "Salary Range",
      "placeholder": "e.g. €60,000 - €80,000",
      "help": "Salary indication (recommended for transparency)"
    },
    "whyNowAngle": {
      "label": "Why Now",
      "placeholder": "e.g. \"With the EU AI Act in force from Q1 2026, brand teams must prove their AI-content audit trail\"",
      "help": "What makes this newsworthy NOW — the journalistic timing-hook"
    },
    "pivotMoment": {
      "label": "Pivot Moment",
      "placeholder": "e.g. \"the moment the customer dared to halve their team\"",
      "help": "The narrative scharnier — the specific scene the story turns on"
    },
    "industryContext": {
      "label": "Industry Context (optional)",
      "placeholder": "e.g. \"in a market where 80% of AI tools still return English-only output\"",
      "help": "Wider industry frame the story sits in (optional)"
    },
    "solutionPhases": {
      "label": "Solution Phases (3-5)",
      "placeholder": "One implementation phase per line:\n- Discovery + audit (week 1-2)\n- Voice-baseline definition (week 3)\n- Team rollout (week 4-6)",
      "help": "3-5 implementation steps — gives the case-study spine and pacing"
    },
    "failureFootnote": {
      "label": "Failure Footnote (optional but credible)",
      "placeholder": "e.g. \"Eerste poging gestrand: voice-guide te abstract; iteratie 2 voegde concrete do/don't-voorbeelden toe\"",
      "help": "What went wrong on the way — adds credibility, breaks hagiography pattern"
    },
    "customerName": {
      "label": "Customer / Company Name",
      "placeholder": "e.g. Acme Corp",
      "help": "The featured customer (use placeholder if confidential)"
    },
    "challengeDescription": {
      "label": "Challenge Description",
      "placeholder": "What problem did the customer face?",
      "help": "The business challenge before your solution"
    },
    "keyMetrics": {
      "label": "Key Results / Metrics",
      "placeholder": "e.g. +40% revenue, 2x conversion rate",
      "help": "Quantifiable results to highlight"
    },
    "customerQuote": {
      "label": "Customer Quote",
      "placeholder": "A testimonial quote from the customer",
      "help": "Direct quote for social proof"
    },
    "differentiatorClaim": {
      "label": "Differentiator Claim",
      "placeholder": "e.g. \"We measure brand voice; competitors only measure visual consistency\"",
      "help": "1 sentence naming the single dimension on which you win — anchors the comparison"
    },
    "tonePosition": {
      "label": "Tone Position",
      "help": "Comparison tone — too aggressive backfires, too soft is wasted breath"
    },
    "seoFocus": {
      "label": "SEO Focus",
      "help": "Optimize headings and meta for search engines"
    },
    "competitors": {
      "label": "Competitors to Compare",
      "placeholder": "Add competitor name…",
      "help": "Which competitors to compare against"
    },
    "comparisonCriteria": {
      "label": "Comparison Criteria",
      "placeholder": "e.g. Price, Features, Support, Integrations",
      "help": "Dimensions to compare on"
    },
    "hookFormat": {
      "label": "Hook Format",
      "help": "Drives the first 1–3 lines / opening seconds"
    },
    "payoffPromise": {
      "label": "Payoff Promise",
      "placeholder": "e.g. \"Een 3-stappen-frame om brand-fluff te detecteren\"",
      "help": "What the reader gets if they keep reading / click through"
    },
    "targetObjection": {
      "label": "Target Objection",
      "placeholder": "e.g. \"marketing-budget al uitgeput\"",
      "help": "Concrete weerstand the copy should address head-on (optional)"
    },
    "proofPoint": {
      "label": "Proof Point",
      "placeholder": "e.g. \"Better Brands +24% voice-fidelity in 4 weken\"",
      "help": "1 stat / quote / customer-fragment for the body (optional)"
    },
    "valueProposition": {
      "label": "Value Proposition",
      "placeholder": "e.g. \"Voor brand-managers die voice-consistency willen meten — zonder eigen taal-team op te bouwen\"",
      "help": "Short, sharp value-prop the ad-copy should anchor on"
    },
    "headlineCount": {
      "label": "Headline Variants (default 2)",
      "placeholder": "2",
      "help": "Number of headline variations to generate (Google search-ad asset best practice: 3-5)"
    },
    "ctaType": {
      "label": "CTA Type"
    },
    "socialProof": {
      "label": "Include Social Proof",
      "help": "Add testimonial or stat to ad copy"
    },
    "landingPageUrl": {
      "label": "Landing Page URL",
      "placeholder": "e.g. https://example.com/offer",
      "help": "Where the CTA should link to"
    },
    "dominantVisualElement": {
      "label": "Dominant Visual Element",
      "placeholder": "e.g. \"product hero shot center, bold contrast badge top-right\"",
      "help": "Display ads have ~1-2 words of copy room — visual focus is essential"
    },
    "cultureSignal": {
      "label": "Culture Signal",
      "placeholder": "e.g. \"team durft elkaar te corrigeren in design-review zonder hiërarchie\"",
      "help": "1 specific cultural behavior the story implicitly demonstrates"
    },
    "employeeName": {
      "label": "Employee Name & Role",
      "placeholder": "e.g. Maria Santos, Lead Designer — 3 years at company",
      "help": "Featured employee details"
    },
    "storyAngle": {
      "label": "Story Angle",
      "help": "Narrative focus of the story"
    },
    "footageType": {
      "label": "Footage Type"
    },
    "textOverlay": {
      "label": "Text Overlay",
      "help": "Style of on-screen text — drives caption rhythm and visual density"
    },
    "colorGrade": {
      "label": "Color Grade",
      "help": "Visual mood — beïnvloedt phrasing en tone (warm = nostalgisch, cool = professioneel, vibrant = energiek, natural = documentary)"
    },
    "videoDuration": {
      "label": "Duration (seconds)",
      "placeholder": "e.g. 30",
      "help": "Target video/audio duration in seconds"
    },
    "sceneSkeleton": {
      "label": "Scene Skeleton",
      "placeholder": "One scene per line:\n- The problem no one names\n- The data that proves it\n- Our approach\n- Evidence from a customer case\n- The next step",
      "help": "One scene per line — used 1-to-1 as the scenes title. Optional: `Title — bullet1; bullet2` for sub-points."
    },
    "sceneHook": {
      "label": "Opening Scene Hook",
      "placeholder": "e.g. \"Most brands don't measure brand voice — we do.\"",
      "help": "Exact opening line for scene 1 (or the piece overall). Make-or-break for engagement."
    },
    "payoffPosition": {
      "label": "Payoff Scene (number)",
      "placeholder": "4",
      "help": "Which scene number lands the payoff (typically 60-70% through the piece)."
    },
    "coreAnalogy": {
      "label": "Core Analogy",
      "placeholder": "e.g. \"brand-voice consistency = a vocal test in a choir — miss one part and it shows\"",
      "help": "The single metaphor the explainer hangs on — explainers stand or fall on this"
    },
    "videoFormat": {
      "label": "Video Format",
      "help": "Production style of the explainer"
    },
    "complexityLevel": {
      "label": "Topic Complexity",
      "help": "Determines explanation depth and jargon level"
    },
    "hashtagStrategy": {
      "label": "Hashtag Strategy",
      "help": "Which kind of hashtags to add at the end of the post"
    },
    "includeEmoji": {
      "label": "Include Emojis",
      "help": "Weave emojis naturally into the post body"
    },
    "postType": {
      "label": "Post Type",
      "help": "Post format determines engagement style"
    },
    "audienceMood": {
      "label": "Audience Mood",
      "help": "Facebook is conversational — mood-input shifts tone significantly"
    },
    "topQuestions": {
      "label": "Top Questions to Answer",
      "placeholder": "Add question…",
      "help": "Most common customer questions"
    },
    "reportingPeriod": {
      "label": "Reporting Period",
      "placeholder": "e.g. FY 2025, Q1-Q2 2026",
      "help": "Time period covered by the report"
    },
    "impactMetrics": {
      "label": "Key Impact Metrics",
      "placeholder": "e.g. CO2 reduced 40%, 500 jobs created, €2M donated",
      "help": "Quantifiable impact data to highlight"
    },
    "stakeholderAudience": {
      "label": "Primary Audience",
      "help": "Who will read this report"
    },
    "esgFramework": {
      "label": "Reporting Framework",
      "help": "ESG/sustainability reporting framework used"
    },
    "captionLength": {
      "label": "Caption Length",
      "help": "Driver for caption-depth and structure"
    },
    "firstLineMagnet": {
      "label": "First-Line Magnet",
      "placeholder": "e.g. \"Stop scrolling. Read this.\"",
      "help": "The exact first line — Instagram truncates after ~125 chars"
    },
    "announcementType": {
      "label": "Announcement Type",
      "help": "Type of internal communication"
    },
    "actionRequired": {
      "label": "Action Required?",
      "help": "Whether employees need to do something"
    },
    "affectedTeams": {
      "label": "Affected Teams / Departments",
      "placeholder": "e.g. Marketing, Sales, Product, All Staff",
      "help": "Who this communication is for"
    },
    "keyRequirements": {
      "label": "Key Requirements",
      "placeholder": "e.g. 5+ years marketing, B2B experience, data-driven",
      "help": "Must-have qualifications"
    },
    "uniquePerks": {
      "label": "Unique Perks / Benefits",
      "placeholder": "e.g. 4-day work week, learning budget, equity",
      "help": "Differentiating benefits to highlight"
    },
    "sectionSkeleton": {
      "label": "Section Skeleton",
      "placeholder": "One section per line:\n- The problem no one names\n- The data that proves it\n- Our approach\n- Evidence from a customer case\n- The next step",
      "help": "One section per line — used 1-to-1 as the sections title. Optional: `Title — bullet1; bullet2` for sub-points."
    },
    "sectionHook": {
      "label": "First Section Hook",
      "placeholder": "e.g. \"Most brands don't measure brand voice — we do.\"",
      "help": "Exact opening line for section 1 (or the piece overall). Make-or-break for engagement."
    },
    "conversionGoal": {
      "label": "Conversion Goal",
      "help": "Primary action visitors should take"
    },
    "trafficSource": {
      "label": "Primary Traffic Source",
      "help": "Where visitors come from affects messaging"
    },
    "adFormat": {
      "label": "Ad Format",
      "help": "LinkedIn ad placement format — for video ads, select the 'LinkedIn Video Ad' content type"
    },
    "personalCredentials": {
      "label": "Personal Credentials",
      "placeholder": "e.g. \"15 jaar brand-strategie bij B2B SaaS, ex-VP Brand bij ACME\"",
      "help": "Why is this author qualified to take this position?"
    },
    "authorPerspective": {
      "label": "Author Perspective",
      "placeholder": "e.g. VP Marketing sharing lessons learned",
      "help": "Professional angle and authority positioning"
    },
    "slideSkeleton": {
      "label": "Slide Skeleton",
      "placeholder": "One slide per line:\n- The problem no one names\n- The data that proves it\n- Our approach\n- Evidence from a customer case\n- The next step",
      "help": "One slide per line — used 1-to-1 as the slides title. Optional: `Title — bullet1; bullet2` for sub-points."
    },
    "slideHook": {
      "label": "First Slide Hook",
      "placeholder": "e.g. \"Most brands don't measure brand voice — we do.\"",
      "help": "Exact opening line for slide 1 (or the piece overall). Make-or-break for engagement."
    },
    "transitionStyle": {
      "label": "Transition Style"
    },
    "includeCtaSlide": {
      "label": "Include CTA Slide",
      "help": "Final slide is a dedicated call-to-action"
    },
    "slidesCount": {
      "label": "Number of Slides",
      "placeholder": "e.g. 8",
      "help": "Target number of slides/cards"
    },
    "narrativeStructure": {
      "label": "Narrative Structure",
      "help": "Slide flow structure"
    },
    "eventName": {
      "label": "Event Name",
      "placeholder": "e.g. Brand Strategy Masterclass 2026",
      "help": "Official event title"
    },
    "eventDate": {
      "label": "Event Date & Time",
      "placeholder": "e.g. June 15, 2026 at 2:00 PM CET",
      "help": "Date, time and timezone"
    },
    "eventUrl": {
      "label": "Registration URL",
      "placeholder": "https://…",
      "help": "Registration or event page link"
    },
    "eventLocation": {
      "label": "Location",
      "placeholder": "e.g. Online (Zoom) or Amsterdam, Netherlands",
      "help": "Physical location or virtual platform"
    },
    "speakers": {
      "label": "Speakers / Hosts",
      "placeholder": "Add speaker name…",
      "help": "Featured speakers or panel members"
    },
    "ctaPlacement": {
      "label": "CTA Placement"
    },
    "previewTextLength": {
      "label": "Preview Text Length (chars)",
      "placeholder": "90",
      "help": "Characters visible in email client preview (30–150)"
    },
    "personalize": {
      "label": "Personalization",
      "help": "Use recipient name and dynamic content"
    },
    "subjectLine": {
      "label": "Subject Line",
      "placeholder": "e.g. Your brand deserves better",
      "help": "Email subject line (AI will also suggest alternatives)"
    },
    "newsletterTheme": {
      "label": "Newsletter Theme",
      "placeholder": "e.g. Weekly brand strategy insights",
      "help": "Recurring theme or series name"
    },
    "pollQuestion": {
      "label": "Poll Question",
      "placeholder": "e.g. What's your biggest brand challenge?",
      "help": "The question to ask (max ~140 chars on LinkedIn)"
    },
    "pollOptions": {
      "label": "Poll Options",
      "placeholder": "Add option…",
      "help": "2-4 answer choices"
    },
    "personalAnecdote": {
      "label": "Lead with Personal Anecdote",
      "help": "Open with a 1-2 sentence personal scene before the argument"
    },
    "hookStrategy": {
      "label": "Hook Strategy (first 3s)",
      "help": "How you stop the scroll in the first 3 seconds (silent autoplay)"
    },
    "captionStyle": {
      "label": "On-screen Caption Style",
      "help": "LinkedIn autoplay is silent — captions are essential for watch-time. Default: burned-in."
    },
    "journalistRecentArticle": {
      "label": "Journalist's Recent Article (reference)",
      "placeholder": "e.g. \"Marketing Week 2026-04-12 — 'Brand-tools die nooit pivoteren'\"",
      "help": "Title or summary of a recent piece by this journalist — pitches without this are auto-deleted"
    },
    "dataPoint": {
      "label": "Hero Data Point",
      "placeholder": "e.g. \"3 in 5 B2B brands don't measure brand voice\"",
      "help": "1 surprising stat / number that anchors the pitch"
    },
    "targetJournalist": {
      "label": "Target Journalist / Publication",
      "placeholder": "e.g. Marketing Week, Adformatie, specific journalist name",
      "help": "Who you're pitching to"
    },
    "exclusiveAngle": {
      "label": "Exclusive Angle",
      "placeholder": "e.g. First look at AI brand strategy tool with exclusive data",
      "help": "What makes this pitch newsworthy for this journalist"
    },
    "editorialPretext": {
      "label": "Editorial Pretext",
      "placeholder": "e.g. \"3 lessons brand managers learned about consistency\"",
      "help": "Editorial framing — what makes this read like content, not an ad"
    },
    "publisherStyle": {
      "label": "Publisher / Editorial Style",
      "placeholder": "e.g. Matches editorial tone of TechCrunch",
      "help": "Native ads should match the host publication's style"
    },
    "emailCount": {
      "label": "Number of Emails",
      "placeholder": "e.g. 5",
      "help": "Emails in the nurture sequence"
    },
    "buyingStage": {
      "label": "Entry Buying Stage",
      "help": "Where leads enter this sequence"
    },
    "keyObjections": {
      "label": "Objections to Address",
      "placeholder": "e.g. Price too high, Not sure about ROI",
      "help": "Common objections to overcome in the sequence"
    },
    "salesAngle": {
      "label": "Sales Angle"
    },
    "includePricing": {
      "label": "Include Pricing Section",
      "help": "Placeholder only — leave off if pricing is custom"
    },
    "subTopicMap": {
      "label": "Sub-Topic Map (3-7 H2s)",
      "placeholder": "One sub-topic per line — becomes an H2:\n- How to define brand-voice operationally\n- Why most voice-guides fail\n- Measuring voice-fidelity",
      "help": "3-7 sub-topics — these become H2 sections + drive internal-linking strategy"
    },
    "internalSubpages": {
      "label": "Internal Sub-Pages to Link (optional)",
      "placeholder": "One URL or page title per line",
      "help": "Existing sub-pages to cross-link from this pillar (optional)"
    },
    "agendaSkeleton": {
      "label": "Agenda item Skeleton",
      "placeholder": "One agenda item per line:\n- The problem no one names\n- The data that proves it\n- Our approach\n- Evidence from a customer case\n- The next step",
      "help": "One agenda item per line — used 1-to-1 as the agenda items title. Optional: `Title — bullet1; bullet2` for sub-points."
    },
    "agendaHook": {
      "label": "Opening Hook",
      "placeholder": "e.g. \"Most brands don't measure brand voice — we do.\"",
      "help": "Exact opening line for agenda item 1 (or the piece overall). Make-or-break for engagement."
    },
    "centralQuestion": {
      "label": "Central Question",
      "placeholder": "e.g. \"Why does brand consistency fail at agencies but succeed in-house?\"",
      "help": "The single question the episode investigates — keeps the conversation focused"
    },
    "episodeFormat": {
      "label": "Episode Format"
    },
    "segmentCount": {
      "label": "Segments (1–8)",
      "placeholder": "3",
      "help": "Number of distinct segments with transitions"
    },
    "introStyle": {
      "label": "Intro Style"
    },
    "includeShowNotes": {
      "label": "Generate Show Notes"
    },
    "includeTranscript": {
      "label": "Generate Transcript"
    },
    "guestInfo": {
      "label": "Guest Name & Bio",
      "placeholder": "e.g. Jane Doe, CEO of BrandCo — 15 years in brand strategy",
      "help": "Guest details for interview-style episodes"
    },
    "newsFact": {
      "label": "News Fact / Announcement",
      "placeholder": "e.g. Launch of new AI-powered brand analysis platform",
      "help": "The newsworthy event or announcement"
    },
    "releaseDate": {
      "label": "Release Date",
      "placeholder": "e.g. June 15, 2026",
      "help": "Publication date (for dateline)"
    },
    "spokespersonQuote": {
      "label": "Spokesperson Quote",
      "placeholder": "e.g. 'This launch represents...' — CEO Name",
      "help": "Quote from company executive"
    },
    "contactInfo": {
      "label": "Press Contact",
      "placeholder": "e.g. press@company.com, +31 20 123 4567",
      "help": "Media contact information"
    },
    "productSpecs": {
      "label": "Product Specifications",
      "placeholder": "Technical specs, dimensions, materials, etc.",
      "help": "Key product details to include"
    },
    "pricingInfo": {
      "label": "Pricing",
      "placeholder": "e.g. €99, starting at €49/month",
      "help": "Product pricing to mention"
    },
    "productId": {
      "label": "Linked product",
      "help": "The product/service from your knowledge section that this page is about"
    },
    "featureBenefitMap": {
      "label": "Feature → Benefit Map",
      "placeholder": "One pair per line — Feature → Benefit:\n- Voice-fidelity scoring → know your copy is on-brand before you publish\n- Template library → 80% fewer review rounds",
      "help": "One Feature → Benefit pair per line. Prevents product pages from becoming feature dumps."
    },
    "musicDirection": {
      "label": "Music / Sound Direction",
      "placeholder": "e.g. Upbeat electronic, corporate ambient, acoustic",
      "help": "Music mood and style guidance"
    },
    "urgencyMechanism": {
      "label": "Urgency Mechanism",
      "help": "Promo emails without an urgency mechanism read as 'nice to know'"
    },
    "socialProofSnippet": {
      "label": "Social Proof Snippet (optional)",
      "placeholder": "e.g. \"\"3x faster than our previous tool\" — Maartje, brand lead at ACME\"",
      "help": "1 customer-quote / metric / case-fragment that supports the offer"
    },
    "offerDetails": {
      "label": "Offer Details",
      "placeholder": "e.g. 30% off annual plans until June 30",
      "help": "The specific offer, discount, or promotion"
    },
    "clientName": {
      "label": "Client / Project Name",
      "placeholder": "e.g. TechCorp Q3 Brand Refresh",
      "help": "Client name for proposal personalization"
    },
    "projectScope": {
      "label": "Project Scope",
      "placeholder": "e.g. Full brand identity redesign including logo, guidelines, and collateral",
      "help": "High-level scope of work"
    },
    "budgetRange": {
      "label": "Budget Range",
      "placeholder": "e.g. €15,000 - €25,000",
      "help": "Budget indication for the proposal"
    },
    "timeline": {
      "label": "Project Timeline",
      "placeholder": "e.g. 6 weeks, starting July 2026",
      "help": "Expected project duration"
    },
    "lastValueDelivered": {
      "label": "Last Value Delivered",
      "placeholder": "e.g. \"last shown interest: brand-voice analyzer for LinkedIn\"",
      "help": "Anchor — what concretely interested the user the last time they engaged"
    },
    "pivotAngle": {
      "label": "Pivot Angle",
      "placeholder": "e.g. \"ask whether the pain is still relevant, not 'we miss you'\"",
      "help": "How the email pivots away from generic 'we miss you'"
    },
    "incentive": {
      "label": "Re-engagement Incentive",
      "placeholder": "e.g. 20% welcome-back discount, exclusive content",
      "help": "What motivates return (discount, exclusive, reminder)"
    },
    "inactivityPeriod": {
      "label": "Inactivity Period",
      "help": "How long the subscriber has been inactive"
    },
    "previousActionContext": {
      "label": "Previous Action Context",
      "placeholder": "e.g. \"viewed pricing page 3 days ago, bounced before signup\"",
      "help": "What the user concretely did — copy must reference this directly"
    },
    "incentiveOffer": {
      "label": "Incentive Offer (optional)",
      "placeholder": "e.g. \"15% off when you sign up this week\"",
      "help": "Optional incentive to overcome the bounce-reason"
    },
    "retargetingSegment": {
      "label": "Retargeting Segment",
      "help": "Which audience segment is being retargeted"
    },
    "productReference": {
      "label": "Product / Page to Reference",
      "placeholder": "e.g. Product X they viewed, pricing page",
      "help": "What the user previously interacted with"
    },
    "centralPainPoint": {
      "label": "Central Pain Point",
      "placeholder": "e.g. \"Inconsistentie kost teams 30% meer review-tijd\"",
      "help": "The single pain the entire piece anchors on (deck/one-pager spine)"
    },
    "competitorContext": {
      "label": "Competitor Context",
      "placeholder": "e.g. \"vs. legacy tools that still review brand voice manually\"",
      "help": "How the deck positions vs. competitors (1 sentence)"
    },
    "targetKeywords": {
      "label": "Target Keywords",
      "placeholder": "Add keyword…",
      "help": "Keywords this ad targets in Google/Bing"
    },
    "adPlatform": {
      "label": "Platform",
      "help": "Social ad platform determines format and copy constraints"
    },
    "adObjective": {
      "label": "Ad Objective",
      "help": "Platform ad objective setting"
    },
    "platform": {
      "label": "Platform",
      "help": "Platform determines format constraints and tone"
    },
    "keyMessages": {
      "label": "Key Messages to Capture",
      "placeholder": "e.g. Time saved, ROI achieved, team adoption",
      "help": "Core points the testimonial should convey"
    },
    "industryNorm": {
      "label": "Industry Norm (the consensus you're challenging)",
      "placeholder": "e.g. \"Most brand consultants treat brand voice as taste — subjective, untestable\"",
      "help": "What does everyone in this space currently believe — that you're about to challenge"
    },
    "trendReference": {
      "label": "Trend / Sound Reference",
      "placeholder": "e.g. 'Day in the life' format, trending audio XYZ",
      "help": "TikTok trend or sound to leverage"
    },
    "threadLength": {
      "label": "Thread Length (tweets)",
      "placeholder": "e.g. 7",
      "help": "Number of tweets in the thread (5-15 recommended)"
    },
    "openingHook": {
      "label": "Opening Tweet — Exact Text",
      "placeholder": "e.g. \"Most B2B brands think consistency slows them down. The opposite is true.\"",
      "help": "The literal first tweet (max 280 chars) — make-or-break for thread engagement"
    },
    "tweetSkeleton": {
      "label": "Tweet Skeleton (optional)",
      "placeholder": "One tweet per line — outline of the thread",
      "help": "Optional: outline tweet-by-tweet (one per line) to lock the structure"
    },
    "hookSecond": {
      "label": "0:00 – 0:03 — Visual Hook",
      "placeholder": "e.g. \"Close-up of hands snapping a notebook shut\"",
      "help": "What happens in the first 3 seconds — make-or-break for skip behavior"
    },
    "payoffMoment": {
      "label": "Payoff Moment (timestamp + scene)",
      "placeholder": "e.g. \"0:18 — split-screen: chaotic-marketing vs. consistent-brand\"",
      "help": "Scene where the value lands for the viewer"
    },
    "skipDeterrent": {
      "label": "Skip Deterrent (0:00 – 0:05)",
      "placeholder": "e.g. \"open with statement that names viewer's exact frustration\"",
      "help": "Specific tactic to prevent skip in the 5-second skippable window"
    },
    "targetTakeaway": {
      "label": "Target Takeaway",
      "placeholder": "e.g. \"A measurable brand voice is an operational choice, not a creative one\"",
      "help": "1 sentence the audience should remember after consuming this piece"
    },
    "webinarFormat": {
      "label": "Webinar Format",
      "help": "Webinar structure"
    },
    "interactionPoints": {
      "label": "Interaction Points",
      "placeholder": "e.g. Poll at 10min, Q&A at 25min, breakout at 35min",
      "help": "Planned audience interaction moments"
    },
    "sendInterval": {
      "label": "Send Interval",
      "help": "Time between emails in the sequence"
    },
    "onboardingSteps": {
      "label": "Key Onboarding Steps",
      "placeholder": "e.g. Setup profile, First project, Invite team",
      "help": "Actions you want new users to complete"
    }
  },
  "options": {
    "articleStructure": {
      "deep-dive": "Deep Dive — single topic, in depth",
      "listicle": "Listicle — numbered list of points",
      "how-to": "How-to Guide — step-by-step instructions",
      "explainer": "Explainer — break down a complex concept",
      "comparison": "Comparison — compare options or approaches",
      "narrative": "Narrative — story-driven arc"
    },
    "optimizationGoals": {
      "seo": "SEO-optimalisatie",
      "geo": "GEO-optimalisatie (AI-citeerbaarheid)"
    },
    "structure": {
      "inverted-pyramid": "Inverted Pyramid — lead first",
      "chronological": "Chronological — timeline / story arc",
      "profile": "Profile — person-centric",
      "impact-report": "Impact Report — metrics + narrative"
    },
    "tonePosition": {
      "factual": "Factual — neutral comparison, let data speak",
      "persuasive": "Persuasive — actively argue your case",
      "diplomatic": "Diplomatic — acknowledge their strengths first"
    },
    "hookFormat": {
      "pattern-interrupt": "Pattern Interrupt — break expected rhythm",
      "question": "Question — open with a probing question",
      "stat": "Stat — surprising number first",
      "contrarian-take": "Contrarian Take — challenge a common belief",
      "story-open": "Story Open — narrative micro-scene",
      "listicle-promise": "Listicle Promise — promise N items / steps"
    },
    "ctaType": {
      "learn-more": "Learn More",
      "sign-up": "Sign Up",
      "shop-now": "Shop Now",
      "contact-us": "Contact Us"
    },
    "storyAngle": {
      "Career Growth": "Career Growth",
      "Day in the Life": "Day in the Life",
      "Project Highlight": "Project Highlight",
      "Culture & Values": "Culture & Values",
      "Innovation Story": "Innovation Story"
    },
    "footageType": {
      "real-person": "Real Person",
      "stock": "Stock Footage",
      "animation": "Animation",
      "mixed": "Mixed"
    },
    "textOverlay": {
      "bold-headlines": "Bold Headlines",
      "minimal": "Minimal",
      "dynamic-captions": "Dynamic Captions"
    },
    "colorGrade": {
      "warm": "Warm",
      "cool": "Cool",
      "vibrant": "Vibrant",
      "natural": "Natural"
    },
    "videoFormat": {
      "Animation / Motion Graphics": "Animation / Motion Graphics",
      "Screen Recording": "Screen Recording",
      "Live Action": "Live Action",
      "Mixed Media": "Mixed Media"
    },
    "complexityLevel": {
      "Simple (consumer)": "Simple (consumer)",
      "Moderate (prosumer)": "Moderate (prosumer)",
      "Complex (technical)": "Complex (technical)"
    },
    "hashtagStrategy": {
      "trending": "Trending — broad reach",
      "niche": "Niche — targeted community",
      "branded": "Branded — own hashtags",
      "mixed": "Mixed — combination",
      "none": "None"
    },
    "postType": {
      "Link Share": "Link Share",
      "Photo": "Photo",
      "Video": "Video",
      "Event": "Event",
      "Status Update": "Status Update"
    },
    "audienceMood": {
      "casual-conversational": "Casual / Conversational — friendly, light",
      "community-rallying": "Community Rallying — calls to shared identity",
      "informative-helpful": "Informative / Helpful — explainer voice",
      "playful-irreverent": "Playful / Irreverent — humor, surprise"
    },
    "stakeholderAudience": {
      "Investors": "Investors",
      "Customers": "Customers",
      "Employees": "Employees",
      "General Public": "General Public",
      "Regulators": "Regulators"
    },
    "esgFramework": {
      "GRI": "GRI",
      "SASB": "SASB",
      "TCFD": "TCFD",
      "B Corp": "B Corp",
      "UN SDGs": "UN SDGs",
      "Custom": "Custom"
    },
    "captionLength": {
      "short": "Short — 1 sentence + emoji",
      "medium": "Medium — 3-5 sentences",
      "long": "Long — micro-essay (5+ sentences)"
    },
    "announcementType": {
      "Company Update": "Company Update",
      "Policy Change": "Policy Change",
      "Product Launch": "Product Launch",
      "Leadership Change": "Leadership Change",
      "Team Achievement": "Team Achievement"
    },
    "conversionGoal": {
      "Email Signup": "Email Signup",
      "Free Trial": "Free Trial",
      "Download": "Download",
      "Purchase": "Purchase",
      "Demo Request": "Demo Request",
      "Contact Form": "Contact Form"
    },
    "trafficSource": {
      "Paid Ads": "Paid Ads",
      "Email": "Email",
      "Organic Search": "Organic Search",
      "Social Media": "Social Media",
      "Referral": "Referral"
    },
    "adFormat": {
      "single-image": "Single Image",
      "message-ad": "Message Ad"
    },
    "transitionStyle": {
      "continuous": "Continuous — content flows across slides",
      "standalone": "Standalone — each slide independent",
      "story-arc": "Story Arc — build toward a conclusion"
    },
    "narrativeStructure": {
      "Listicle (tips/steps)": "Listicle (tips/steps)",
      "Before & After": "Before & After",
      "Problem → Solution": "Problem → Solution",
      "Data Story": "Data Story",
      "How-To Guide": "How-To Guide"
    },
    "ctaPlacement": {
      "above-fold": "Above the Fold",
      "bottom": "Bottom",
      "multiple": "Multiple CTAs",
      "inline": "Inline"
    },
    "hookStrategy": {
      "bold-statement": "Bold statement / counterintuitive claim",
      "question": "Open question",
      "pattern-interrupt": "Pattern-interrupt visual",
      "stat-shock": "Surprising statistic",
      "story-open": "Mid-scene story-open"
    },
    "captionStyle": {
      "burned-in": "Burned-in captions (always visible)",
      "auto-closed": "Auto-generated closed captions",
      "key-phrases": "Key-phrase overlays (highlights only)"
    },
    "buyingStage": {
      "Awareness": "Awareness",
      "Consideration": "Consideration",
      "Evaluation": "Evaluation",
      "Decision": "Decision"
    },
    "salesAngle": {
      "problem-solution": "Problem → Solution — pain-led",
      "benefit-led": "Benefit-led — lead with outcomes",
      "feature-focused": "Feature-focused — capability breakdown",
      "social-proof": "Social Proof — customer wins first",
      "competitive": "Competitive — differentiate vs alternatives"
    },
    "episodeFormat": {
      "solo": "Solo",
      "interview": "Interview",
      "panel": "Panel",
      "narrative": "Narrative"
    },
    "introStyle": {
      "cold-open": "Cold Open — jump straight in",
      "teaser": "Teaser — preview key takeaways",
      "music-intro": "Music Intro — theme music + host intro"
    },
    "urgencyMechanism": {
      "deadline": "Deadline — date/time-bound",
      "scarcity": "Scarcity — limited inventory / seats",
      "loss-aversion": "Loss Aversion — what they lose by not acting",
      "none": "None — evergreen / no manufactured urgency"
    },
    "inactivityPeriod": {
      "30 days": "30 days",
      "60 days": "60 days",
      "90 days": "90 days",
      "6+ months": "6+ months"
    },
    "retargetingSegment": {
      "Cart Abandonment": "Cart Abandonment",
      "Page Visitors": "Page Visitors",
      "Past Customers": "Past Customers",
      "Email Subscribers": "Email Subscribers",
      "Video Viewers": "Video Viewers"
    },
    "adPlatform": {
      "Facebook": "Facebook",
      "Instagram": "Instagram",
      "LinkedIn": "LinkedIn",
      "TikTok": "TikTok"
    },
    "adObjective": {
      "Traffic": "Traffic",
      "Conversions": "Conversions",
      "Lead Generation": "Lead Generation",
      "Brand Awareness": "Brand Awareness",
      "Engagement": "Engagement"
    },
    "platform": {
      "Instagram": "Instagram",
      "LinkedIn": "LinkedIn",
      "Facebook": "Facebook"
    },
    "webinarFormat": {
      "Presentation + Q&A": "Presentation + Q&A",
      "Panel Discussion": "Panel Discussion",
      "Workshop / Hands-on": "Workshop / Hands-on",
      "Interview": "Interview",
      "Demo": "Demo"
    },
    "sendInterval": {
      "Daily": "Daily",
      "Every 2 Days": "Every 2 Days",
      "Every 3 Days": "Every 3 Days",
      "Weekly": "Weekly"
    }
  },
  "byType": {
    "employer-brand-video": {
      "storyAngle": {
        "label": "Video Focus",
        "help": "Video narrative focus",
        "options": {
          "Culture Overview": "Culture Overview",
          "Employee Testimonials": "Employee Testimonials",
          "Office / Workspace Tour": "Office / Workspace Tour",
          "Team Collaboration": "Team Collaboration",
          "Impact & Mission": "Impact & Mission"
        }
      }
    },
    "job-ad-copy": {
      "jobTitle": {
        "label": "Job Title",
        "placeholder": "e.g. Marketing Manager",
        "help": "Position title"
      }
    },
    "landing-page": {
      "payoffPosition": {
        "label": "Payoff Section (number)",
        "placeholder": "4",
        "help": "Which section number lands the payoff (typically 60-70% through the piece)."
      },
      "socialProof": {
        "label": "Available Social Proof",
        "placeholder": "e.g. Client logos, testimonials, stats",
        "help": "Trust elements to include on the page"
      }
    },
    "linkedin-article": {
      "seoKeyword": {
        "label": "SEO Keyword",
        "placeholder": "e.g. brand positioning strategy",
        "help": "Optional — helps the AI focus the angle. Leave blank if you have no target keyword."
      }
    },
    "linkedin-carousel": {
      "payoffPosition": {
        "label": "Payoff Slide (number)",
        "placeholder": "4",
        "help": "Which slide number lands the payoff (typically 60-70% through the piece)."
      }
    },
    "linkedin-post": {
      "postType": {
        "label": "Post Type",
        "help": "Determines structure and tone",
        "options": {
          "Thought Leadership": "Thought Leadership",
          "Company News": "Company News",
          "Personal Story": "Personal Story",
          "Industry Insight": "Industry Insight",
          "Poll / Question": "Poll / Question",
          "Case Study Snippet": "Case Study Snippet"
        }
      }
    },
    "linkedin-video": {
      "videoFormat": {
        "label": "Video Format",
        "help": "Production style",
        "options": {
          "Talking Head": "Talking Head",
          "Screen Recording": "Screen Recording",
          "Animation": "Animation",
          "B-Roll Montage": "B-Roll Montage"
        }
      }
    },
    "one-pager": {
      "keyMetrics": {
        "label": "Proof Points",
        "placeholder": "e.g. 500+ customers, 99.9% uptime",
        "help": "Quantifiable proof of value"
      }
    },
    "podcast-outline": {
      "payoffPosition": {
        "label": "Payoff Agenda item (number)",
        "placeholder": "4",
        "help": "Which agenda item number lands the payoff (typically 60-70% through the piece)."
      }
    },
    "product-page": {
      "productSpecs": {
        "label": "Extra product specs (optional)",
        "placeholder": "e.g. Dimensions, materials, compatibility, pricing",
        "help": "Additional specs on top of the linked product — only what isn't already in the product record"
      },
      "pricingInfo": {
        "label": "Pricing Information",
        "placeholder": "e.g. Starting at €49/month, free tier available",
        "help": "Pricing to display or reference"
      }
    },
    "sales-deck": {
      "payoffPosition": {
        "label": "Payoff Slide (number)",
        "placeholder": "4",
        "help": "Which slide number lands the payoff (typically 60-70% through the piece)."
      },
      "pricingInfo": {
        "label": "Pricing / Investment",
        "placeholder": "e.g. Starting at €5K/month, custom enterprise pricing",
        "help": "Pricing information to include in the deck"
      },
      "keyMetrics": {
        "label": "Proof Points / Metrics",
        "placeholder": "e.g. 150+ clients, 40% avg ROI increase",
        "help": "Quantifiable results and credentials"
      }
    },
    "search-ad": {
      "headlineCount": {
        "label": "Headline Variants (default 3)",
        "placeholder": "3",
        "help": "Number of headline variations to generate (Google search-ad asset best practice: 3-5)"
      }
    },
    "social-carousel": {
      "payoffPosition": {
        "label": "Payoff Slide (number)",
        "placeholder": "4",
        "help": "Which slide number lands the payoff (typically 60-70% through the piece)."
      },
      "narrativeStructure": {
        "label": "Slide Narrative",
        "help": "How slides connect into a story",
        "options": {
          "Listicle": "Listicle",
          "Before & After": "Before & After",
          "Problem → Solution": "Problem → Solution",
          "Step-by-Step": "Step-by-Step",
          "Data Story": "Data Story"
        }
      }
    },
    "testimonial-video": {
      "customerName": {
        "label": "Featured Customer",
        "placeholder": "e.g. Sarah Chen, VP Marketing at TechCorp",
        "help": "Customer name and title for the testimonial"
      }
    },
    "thought-leadership": {
      "authorPerspective": {
        "label": "Author / Executive Perspective",
        "placeholder": "e.g. CEO viewpoint on industry disruption",
        "help": "Whose perspective and what contrarian angle"
      }
    },
    "video-ad": {
      "adPlatform": {
        "label": "Platform",
        "help": "Platform determines pacing and skip behavior",
        "options": {
          "YouTube Pre-Roll": "YouTube Pre-Roll",
          "YouTube Bumper (6s)": "YouTube Bumper (6s)",
          "Social Feed": "Social Feed",
          "Connected TV": "Connected TV"
        }
      }
    },
    "webinar-outline": {
      "payoffPosition": {
        "label": "Payoff Agenda item (number)",
        "placeholder": "4",
        "help": "Which agenda item number lands the payoff (typically 60-70% through the piece)."
      },
      "speakers": {
        "label": "Speakers / Hosts",
        "placeholder": "Add speaker name…",
        "help": "Presenter names and titles"
      }
    },
    "welcome-sequence": {
      "emailCount": {
        "label": "Number of Emails",
        "placeholder": "e.g. 5",
        "help": "Emails in the welcome sequence (3-7 typical)"
      }
    }
  }
} as const;

export default ns;
