// Canonical (source-of-truth) English UI strings — `common` namespace.
// Non-English bundles are generated by the AI translation pipeline
// (tasks/i18n-ai-translation-pipeline.md). nl is hand-seeded for now.
const common = {
  appearance: {
    title: 'Appearance',
    displayLanguageTitle: 'Display language',
    displayLanguageHelp:
      'Language for menus, buttons and labels across Branddock. This does not change the language your content is written in.',
    scopeOnlyYou: 'Only you',
    saved: 'Display language updated',
    saveFailed: 'Could not update display language',
  },
} as const;

export default common;
