// =============================================================
// Default MediumEnrichment-rijen (platform/format-specs, componentTemplates,
// best practices, phase guidance) — GEDEELDE bron voor prisma/seed.ts én de
// admin-repair-route. Waarom: prod krijgt alleen `prisma db push` (geen seed),
// waardoor deze defaults daar ontbraken en élke canvas-generatie afbrak op
// "No component template resolved" (2026-07-16, pilot-incident).
// =============================================================

export interface MediumEnrichmentDefault {
  platform: string;
  format: string;
  specs: object;
  componentTemplate: object[];
  bestPractices: object;
  phaseGuidance: object;
  optimalPublishTimes: object;
}

export const MEDIUM_ENRICHMENT_DEFAULTS: MediumEnrichmentDefault[] = [
  {
    platform: "linkedin",
    format: "organic-post",
    specs: { maxChars: { headline: 150, body: 3000 }, imageSize: { width: 1200, height: 627 }, videoMaxDuration: 600 },
    componentTemplate: [
      { type: "hook", required: true, maxLength: 150 },
      { type: "body", required: true, maxLength: 3000 },
      { type: "cta", required: false, maxLength: 100 },
      { type: "hashtags", required: false, maxLength: 200 },
      { type: "image", required: false },
    ],
    bestPractices: [
      "Open with a bold statement or question in the first line",
      "Use line breaks for readability — avoid walls of text",
      "Include a clear CTA in the last line",
      "Tag relevant people or companies for reach",
      "Post between Tuesday-Thursday, 8-10 AM for best engagement",
      "Use 3-5 relevant hashtags at the end",
      "Personal stories outperform corporate announcements 3:1",
    ],
    phaseGuidance: {
      awareness: { toneShift: "thought-provoking", messageFrame: "industry challenge", ctaType: "learn-more", hookStrategy: "contrarian take or surprising stat", visualDirection: "data visualization or team photo" },
      consideration: { toneShift: "educational", messageFrame: "how-we-solve-it", ctaType: "download-resource", hookStrategy: "case study teaser or framework introduction", visualDirection: "infographic or process diagram" },
      decision: { toneShift: "confident", messageFrame: "proof-and-results", ctaType: "book-demo", hookStrategy: "customer quote or ROI metric", visualDirection: "testimonial card or comparison chart" },
      retention: { toneShift: "celebratory", messageFrame: "customer-success", ctaType: "share-your-story", hookStrategy: "milestone or achievement spotlight", visualDirection: "customer spotlight or behind-the-scenes" },
      advocacy: { toneShift: "collaborative", messageFrame: "community-building", ctaType: "refer-a-friend", hookStrategy: "user-generated content or community highlight", visualDirection: "community collage or co-created content" },
    },
    optimalPublishTimes: { dayOfWeek: [2, 3, 4], hourRange: [8, 10], timezone: "Europe/Amsterdam" },
  },
  {
    platform: "linkedin",
    format: "ad",
    specs: { maxChars: { headline: 70, body: 150, description: 100 }, imageSize: { width: 1200, height: 627 }, carouselCards: { min: 2, max: 10 } },
    componentTemplate: [
      { type: "headline", required: true, maxLength: 70 },
      { type: "body", required: true, maxLength: 150 },
      { type: "description", required: false, maxLength: 100 },
      { type: "cta-button", required: true },
      { type: "image", required: true },
    ],
    bestPractices: [
      "Lead with the value proposition, not the brand name",
      "Use numbers and specifics in headlines (e.g., '3x faster')",
      "Include social proof when possible",
      "Test single image vs carousel — carousel often wins for B2B",
      "Keep body copy under 100 characters for mobile readability",
      "Use a clear, action-oriented CTA button text",
    ],
    phaseGuidance: {
      awareness: { toneShift: "curiosity-driven", messageFrame: "problem-awareness", ctaType: "Learn More", hookStrategy: "pain point headline", visualDirection: "attention-grabbing visual with minimal text" },
      consideration: { toneShift: "authoritative", messageFrame: "solution-positioning", ctaType: "Download", hookStrategy: "comparison or framework", visualDirection: "product screenshot or demo preview" },
      decision: { toneShift: "urgent", messageFrame: "offer-driven", ctaType: "Sign Up", hookStrategy: "limited offer or proof point", visualDirection: "testimonial or ROI stats" },
      retention: { toneShift: "exclusive", messageFrame: "insider-value", ctaType: "Explore", hookStrategy: "new feature or upgrade", visualDirection: "product feature highlight" },
      advocacy: { toneShift: "empowering", messageFrame: "success-story", ctaType: "Share", hookStrategy: "customer achievement", visualDirection: "customer spotlight" },
    },
    optimalPublishTimes: { dayOfWeek: [1, 2, 3, 4, 5], hourRange: [9, 17], timezone: "Europe/Amsterdam" },
  },
  {
    platform: "instagram",
    format: "feed-post",
    specs: { maxChars: { caption: 2200 }, imageSize: { width: 1080, height: 1080 }, videoMaxDuration: 60 },
    componentTemplate: [
      { type: "hook-line", required: true, maxLength: 125 },
      { type: "caption", required: true, maxLength: 2200 },
      { type: "hashtags", required: false, maxLength: 500 },
      { type: "image", required: true },
    ],
    bestPractices: [
      "First line must hook — only 125 chars show before 'more'",
      "Use storytelling and emotional language",
      "Include a call-to-action in the caption",
      "Mix branded and community hashtags (20-30 total)",
      "Carousel posts get 1.4x more reach than single images",
      "Use alt text for accessibility",
      "Authentic, less polished content often outperforms studio shots",
    ],
    phaseGuidance: {
      awareness: { toneShift: "inspiring", messageFrame: "brand-world", ctaType: "save-this-post", hookStrategy: "visually striking image with curiosity-gap caption", visualDirection: "lifestyle photography or bold typography" },
      consideration: { toneShift: "educational", messageFrame: "tips-and-how-to", ctaType: "link-in-bio", hookStrategy: "carousel with actionable steps", visualDirection: "infographic or step-by-step visual" },
      decision: { toneShift: "authentic", messageFrame: "social-proof", ctaType: "dm-us", hookStrategy: "before/after or transformation", visualDirection: "real customer photo or unboxing" },
      retention: { toneShift: "personal", messageFrame: "behind-the-scenes", ctaType: "comment-below", hookStrategy: "team spotlight or process reveal", visualDirection: "candid team photo or workspace shot" },
      advocacy: { toneShift: "celebratory", messageFrame: "user-spotlight", ctaType: "tag-a-friend", hookStrategy: "repost user content or share win", visualDirection: "user-generated content with brand overlay" },
    },
    optimalPublishTimes: { dayOfWeek: [1, 3, 5], hourRange: [11, 13], timezone: "Europe/Amsterdam" },
  },
  {
    platform: "instagram",
    format: "carousel",
    specs: { maxChars: { caption: 2200, slideText: 200 }, imageSize: { width: 1080, height: 1080 }, slides: { min: 2, max: 10 } },
    componentTemplate: [
      { type: "cover-slide", required: true },
      { type: "content-slides", required: true, minCount: 2, maxCount: 9 },
      { type: "cta-slide", required: true },
      { type: "caption", required: true, maxLength: 2200 },
      { type: "hashtags", required: false },
    ],
    bestPractices: [
      "Cover slide must create scroll-stopping curiosity",
      "Each slide should deliver one clear idea",
      "Use consistent visual style and typography across all slides",
      "End with a strong CTA slide (save, share, follow)",
      "Aim for 7-10 slides for optimal engagement",
      "Include text on slides — many watch without sound context",
      "Number slides (1/8, 2/8) to encourage swiping",
    ],
    phaseGuidance: {
      awareness: { toneShift: "educational", messageFrame: "myth-busting or listicle", ctaType: "save-for-later", hookStrategy: "bold claim on cover + proof in slides", visualDirection: "clean typography, brand colors, minimal imagery" },
      consideration: { toneShift: "detailed", messageFrame: "framework-or-process", ctaType: "link-in-bio", hookStrategy: "step-by-step guide or comparison", visualDirection: "diagram slides with clear hierarchy" },
      decision: { toneShift: "persuasive", messageFrame: "case-study-story", ctaType: "dm-for-details", hookStrategy: "transformation story slide by slide", visualDirection: "before/after or timeline progression" },
      retention: { toneShift: "insider", messageFrame: "tips-and-tricks", ctaType: "share-with-someone", hookStrategy: "advanced tips only for followers", visualDirection: "branded template with tips format" },
      advocacy: { toneShift: "community", messageFrame: "user-stories", ctaType: "create-your-own", hookStrategy: "collection of community contributions", visualDirection: "diverse user photos with quotes" },
    },
    optimalPublishTimes: { dayOfWeek: [2, 4, 6], hourRange: [10, 12], timezone: "Europe/Amsterdam" },
  },
  {
    platform: "email",
    format: "newsletter",
    specs: { maxChars: { subject: 60, preheader: 100, body: 5000 }, imageWidth: 600 },
    componentTemplate: [
      { type: "subject-line", required: true, maxLength: 60 },
      { type: "preheader", required: true, maxLength: 100 },
      { type: "hero-image", required: false },
      { type: "headline", required: true, maxLength: 100 },
      { type: "body", required: true, maxLength: 5000 },
      { type: "cta-button", required: true },
      { type: "footer", required: false },
    ],
    bestPractices: [
      "Subject line under 50 characters for mobile display",
      "Use preheader text to complement the subject line",
      "Single primary CTA — avoid decision paralysis",
      "Use the inverted pyramid: most important info first",
      "Test send times — typically Tuesday-Thursday mornings perform best",
      "Keep total width at 600px for email client compatibility",
      "Include plain text alternative for accessibility",
    ],
    phaseGuidance: {
      awareness: { toneShift: "welcoming", messageFrame: "introduction-and-value", ctaType: "explore-resource", hookStrategy: "curiosity-gap subject line", visualDirection: "clean hero image, warm colors" },
      consideration: { toneShift: "helpful", messageFrame: "educational-content", ctaType: "read-more", hookStrategy: "exclusive insight or data point", visualDirection: "infographic or chart in hero" },
      decision: { toneShift: "compelling", messageFrame: "offer-or-trial", ctaType: "start-now", hookStrategy: "urgency or scarcity in subject", visualDirection: "product screenshot or pricing visual" },
      retention: { toneShift: "appreciative", messageFrame: "insider-updates", ctaType: "check-it-out", hookStrategy: "personalized subject with name or behavior", visualDirection: "personalized recommendation or digest" },
      advocacy: { toneShift: "grateful", messageFrame: "referral-program", ctaType: "invite-a-friend", hookStrategy: "reward or recognition in subject", visualDirection: "milestone or achievement visual" },
    },
    optimalPublishTimes: { dayOfWeek: [2, 3, 4], hourRange: [9, 11], timezone: "Europe/Amsterdam" },
  },
  {
    platform: "web",
    format: "landing-page",
    specs: { maxChars: { headline: 80, subheadline: 150, body: 3000 }, heroImageSize: { width: 1440, height: 600 } },
    componentTemplate: [
      { type: "headline", required: true, maxLength: 80 },
      { type: "subheadline", required: true, maxLength: 150 },
      { type: "hero-image", required: false },
      { type: "value-proposition", required: true },
      { type: "benefits-list", required: true },
      { type: "social-proof", required: false },
      { type: "cta-primary", required: true },
      { type: "cta-secondary", required: false },
    ],
    bestPractices: [
      "One page, one goal — remove navigation distractions",
      "Headline should communicate the primary benefit in under 10 words",
      "Place CTA above the fold and repeat it after each section",
      "Use social proof near the CTA (testimonials, logos, numbers)",
      "Optimize for mobile first — 60%+ of traffic is mobile",
      "Use directional cues (arrows, gaze direction) toward CTA",
      "A/B test headlines — they affect conversion rate more than anything else",
    ],
    phaseGuidance: {
      awareness: { toneShift: "inspirational", messageFrame: "problem-solution", ctaType: "learn-more", hookStrategy: "bold headline addressing pain point", visualDirection: "hero image showing transformation" },
      consideration: { toneShift: "informative", messageFrame: "feature-benefit", ctaType: "get-started-free", hookStrategy: "comparison or feature matrix", visualDirection: "product demo or screenshot" },
      decision: { toneShift: "reassuring", messageFrame: "guarantee-and-proof", ctaType: "buy-now", hookStrategy: "risk reversal + social proof", visualDirection: "testimonial video or trust badges" },
      retention: { toneShift: "exclusive", messageFrame: "upgrade-unlock", ctaType: "upgrade", hookStrategy: "loyalty benefit or new feature", visualDirection: "feature comparison or roadmap" },
      advocacy: { toneShift: "empowering", messageFrame: "partner-program", ctaType: "become-partner", hookStrategy: "earning potential or impact metrics", visualDirection: "partner success stories" },
    },
    optimalPublishTimes: { dayOfWeek: [1, 2, 3, 4, 5], hourRange: [8, 18], timezone: "Europe/Amsterdam" },
  },
  {
    platform: "web",
    format: "blog-article",
    specs: { maxChars: { title: 70, metaDescription: 160, body: 15000 }, heroImageSize: { width: 1200, height: 630 } },
    componentTemplate: [
      { type: "title", required: true, maxLength: 70 },
      { type: "meta-description", required: true, maxLength: 160 },
      { type: "hero-image", required: false },
      { type: "introduction", required: true },
      { type: "body-sections", required: true },
      { type: "conclusion", required: true },
      { type: "cta", required: false },
    ],
    bestPractices: [
      "Title should include primary keyword and be under 60 characters for SEO",
      "Write a compelling meta description (155 chars) with a value proposition",
      "Use H2/H3 headers every 300 words for scannability",
      "Include internal and external links (2-3 each per 1000 words)",
      "Aim for 1500-2500 words for SEO performance",
      "Add alt text to all images with relevant keywords",
      "Include a clear next step or CTA at the end",
    ],
    phaseGuidance: {
      awareness: { toneShift: "informative", messageFrame: "problem-education", ctaType: "subscribe-newsletter", hookStrategy: "question or surprising statistic in title", visualDirection: "stock photo or custom illustration" },
      consideration: { toneShift: "expert", messageFrame: "how-to-guide", ctaType: "download-guide", hookStrategy: "practical framework or methodology", visualDirection: "diagrams, screenshots, or process photos" },
      decision: { toneShift: "persuasive", messageFrame: "comparison-review", ctaType: "try-free", hookStrategy: "versus comparison or buyer's guide format", visualDirection: "comparison tables or feature screenshots" },
      retention: { toneShift: "insider", messageFrame: "advanced-tips", ctaType: "join-community", hookStrategy: "pro tips or advanced techniques", visualDirection: "detailed walkthroughs with annotated screenshots" },
      advocacy: { toneShift: "collaborative", messageFrame: "guest-post-or-interview", ctaType: "contribute", hookStrategy: "expert interview or community roundup", visualDirection: "contributor photos or community event images" },
    },
    optimalPublishTimes: { dayOfWeek: [1, 2, 3], hourRange: [8, 10], timezone: "Europe/Amsterdam" },
  },
  {
    platform: "tiktok",
    format: "video",
    specs: { maxChars: { caption: 2200, onScreenText: 100 }, videoSize: { width: 1080, height: 1920 }, videoDuration: { min: 15, max: 180, optimalRange: [30, 60] } },
    componentTemplate: [
      { type: "hook", required: true, maxLength: 50, timing: "0-3s" },
      { type: "body-script", required: true, timing: "3-50s" },
      { type: "cta", required: true, maxLength: 50, timing: "last-5s" },
      { type: "on-screen-text", required: false },
      { type: "caption", required: true, maxLength: 2200 },
      { type: "hashtags", required: false },
      { type: "sound", required: false },
    ],
    bestPractices: [
      "Hook in the first 1-3 seconds — viewers decide to stay or scroll",
      "Use on-screen text for key messages (many watch without sound)",
      "Keep it between 30-60 seconds for optimal completion rate",
      "Shoot vertically (9:16) — never repurpose horizontal video",
      "Use trending sounds when relevant to your message",
      "End with a question or CTA to drive comments",
      "Post 1-3 times per day for algorithm favor",
      "Show faces — videos with people get 2x more engagement",
    ],
    phaseGuidance: {
      awareness: { toneShift: "entertaining", messageFrame: "trend-riding", ctaType: "follow-for-more", hookStrategy: "trending format with brand twist", visualDirection: "fast-paced cuts, trending audio, bold text overlay" },
      consideration: { toneShift: "educational", messageFrame: "quick-tutorial", ctaType: "link-in-bio", hookStrategy: "did-you-know or myth-busting format", visualDirection: "talking head with B-roll cutaways" },
      decision: { toneShift: "authentic", messageFrame: "unboxing-or-demo", ctaType: "tap-to-shop", hookStrategy: "product reveal or transformation", visualDirection: "close-up product shots with natural lighting" },
      retention: { toneShift: "personal", messageFrame: "behind-the-scenes", ctaType: "comment-what-you-think", hookStrategy: "day-in-the-life or process reveal", visualDirection: "casual, authentic filming style" },
      advocacy: { toneShift: "community", messageFrame: "duet-or-stitch", ctaType: "stitch-this", hookStrategy: "challenge or duet invitation", visualDirection: "user-generated content compilation" },
    },
    optimalPublishTimes: { dayOfWeek: [2, 4, 6, 0], hourRange: [12, 15], timezone: "Europe/Amsterdam" },
  },
  {
    platform: "tiktok",
    format: "story",
    specs: { maxChars: { caption: 300, onScreenText: 80 }, videoSize: { width: 1080, height: 1920 }, videoDuration: { min: 5, max: 60, optimalRange: [10, 15] } },
    componentTemplate: [
      { type: "hook", required: true, maxLength: 30, timing: "0-2s" },
      { type: "body-script", required: true, timing: "2-12s" },
      { type: "cta-sticker", required: false },
      { type: "caption", required: false, maxLength: 300 },
    ],
    bestPractices: [
      "Stories are ephemeral — create urgency with limited-time messages",
      "Use stickers, polls, and questions for interaction",
      "Keep it under 15 seconds for highest completion rate",
      "Vertical only (9:16) — fill the screen completely",
      "Tap-through rate drops after 3 stories in a row",
      "Use music or voiceover — stories without audio underperform",
    ],
    phaseGuidance: {
      awareness: { toneShift: "playful", messageFrame: "quick-reveal", ctaType: "swipe-up", hookStrategy: "countdown or teaser", visualDirection: "bright, high-contrast, fast cuts" },
      consideration: { toneShift: "informative", messageFrame: "quick-tip", ctaType: "tap-link", hookStrategy: "one-tip-per-story sequence", visualDirection: "talking head with text overlay" },
      decision: { toneShift: "direct", messageFrame: "flash-offer", ctaType: "shop-now", hookStrategy: "limited-time reveal", visualDirection: "product close-up with price overlay" },
      retention: { toneShift: "casual", messageFrame: "day-in-the-life", ctaType: "reply", hookStrategy: "behind-the-scenes moment", visualDirection: "raw, unedited footage" },
      advocacy: { toneShift: "interactive", messageFrame: "poll-or-question", ctaType: "vote", hookStrategy: "this-or-that or quiz format", visualDirection: "interactive sticker overlays" },
    },
    optimalPublishTimes: { dayOfWeek: [1, 3, 5, 0], hourRange: [18, 21], timezone: "Europe/Amsterdam" },
  },
  {
    platform: "youtube",
    format: "short",
    specs: { maxChars: { title: 100, description: 200 }, videoSize: { width: 1080, height: 1920 }, videoDuration: { min: 15, max: 60, optimalRange: [30, 45] } },
    componentTemplate: [
      { type: "hook", required: true, maxLength: 40, timing: "0-3s" },
      { type: "body-script", required: true, timing: "3-55s" },
      { type: "cta", required: true, timing: "last-5s" },
      { type: "title", required: true, maxLength: 100 },
      { type: "description", required: false, maxLength: 200 },
      { type: "hashtags", required: false },
    ],
    bestPractices: [
      "First 3 seconds decide if viewers stay — hook immediately",
      "Optimal length is 30-45 seconds for the algorithm",
      "Use on-screen text for key points (many watch muted)",
      "Vertical format only (9:16) — never letterbox horizontal content",
      "Loop-friendly endings boost replay and watch time",
      "Post 3-5 Shorts per week for consistent algorithm push",
      "End with a subscribe CTA or question to drive interaction",
    ],
    phaseGuidance: {
      awareness: { toneShift: "attention-grabbing", messageFrame: "surprising-fact", ctaType: "subscribe", hookStrategy: "bold claim or visual shock in first 2 seconds", visualDirection: "fast cuts, bold text, high energy" },
      consideration: { toneShift: "educational", messageFrame: "quick-how-to", ctaType: "watch-full-video", hookStrategy: "numbered tips or one-minute explainer", visualDirection: "talking head with B-roll inserts" },
      decision: { toneShift: "demonstrative", messageFrame: "product-in-action", ctaType: "link-in-description", hookStrategy: "transformation or before/after reveal", visualDirection: "close-up product demo" },
      retention: { toneShift: "entertaining", messageFrame: "series-content", ctaType: "follow-for-part-2", hookStrategy: "cliffhanger or series hook", visualDirection: "branded series template" },
      advocacy: { toneShift: "reactive", messageFrame: "reaction-or-reply", ctaType: "comment-your-take", hookStrategy: "respond to trending topic or comment", visualDirection: "reaction format with original content inset" },
    },
    optimalPublishTimes: { dayOfWeek: [1, 3, 5, 6], hourRange: [14, 17], timezone: "Europe/Amsterdam" },
  },
  {
    platform: "youtube",
    format: "video",
    specs: { maxChars: { title: 100, description: 5000 }, videoSize: { width: 1920, height: 1080 }, videoDuration: { min: 60, max: 3600, optimalRange: [480, 900] } },
    componentTemplate: [
      { type: "hook", required: true, maxLength: 80, timing: "0-30s" },
      { type: "intro", required: true, timing: "30-60s" },
      { type: "body-sections", required: true },
      { type: "cta-mid-roll", required: false },
      { type: "conclusion", required: true, timing: "last-60s" },
      { type: "title", required: true, maxLength: 100 },
      { type: "description", required: true, maxLength: 5000 },
      { type: "tags", required: false },
      { type: "thumbnail-concept", required: true },
    ],
    bestPractices: [
      "Thumbnail and title drive 90% of click-through rate",
      "Hook viewers in the first 30 seconds — state the value promise",
      "Optimal length is 8-15 minutes for monetization and algorithm",
      "Use chapters (timestamps) for better SEO and viewer retention",
      "Include cards and end screens to boost session time",
      "Publish on a consistent schedule for subscriber retention",
      "Description should include key timestamps, links, and keywords",
      "Add subtitles/CC for accessibility and 15% longer watch time",
    ],
    phaseGuidance: {
      awareness: { toneShift: "authoritative", messageFrame: "deep-dive-explainer", ctaType: "subscribe-and-bell", hookStrategy: "promise a framework or revelation in the first 15s", visualDirection: "professional setup, B-roll, graphics package" },
      consideration: { toneShift: "educational", messageFrame: "tutorial-or-review", ctaType: "download-template", hookStrategy: "show the end result first, then teach the process", visualDirection: "screen recording + talking head combo" },
      decision: { toneShift: "transparent", messageFrame: "honest-review-or-comparison", ctaType: "try-link-below", hookStrategy: "head-to-head comparison or honest assessment", visualDirection: "split-screen comparison, data overlays" },
      retention: { toneShift: "personal", messageFrame: "vlog-or-update", ctaType: "join-community", hookStrategy: "personal story or milestone", visualDirection: "cinematic B-roll, authentic moments" },
      advocacy: { toneShift: "collaborative", messageFrame: "interview-or-collab", ctaType: "check-their-channel", hookStrategy: "guest expert or collab teaser", visualDirection: "dual-camera interview setup" },
    },
    optimalPublishTimes: { dayOfWeek: [4, 5, 6], hourRange: [14, 16], timezone: "Europe/Amsterdam" },
  },
  {
    platform: "video",
    format: "script",
    specs: { maxChars: { title: 100, script: 10000 }, videoDuration: { min: 30, max: 600, optimalRange: [60, 180] } },
    componentTemplate: [
      { type: "title", required: true, maxLength: 100 },
      { type: "hook", required: true, maxLength: 200 },
      { type: "script-body", required: true, maxLength: 10000 },
      { type: "visual-directions", required: false },
      { type: "cta", required: true },
      { type: "voiceover-notes", required: false },
    ],
    bestPractices: [
      "Write for the ear, not the eye — read scripts aloud",
      "Include visual direction notes alongside dialogue",
      "Keep sentences short (10-15 words max) for natural delivery",
      "Front-load the hook — attention drops after 8 seconds",
      "Include B-roll suggestions to maintain visual interest",
      "Mark emphasis and pause points for the narrator",
    ],
    phaseGuidance: {
      awareness: { toneShift: "cinematic", messageFrame: "story-driven", ctaType: "discover-more", hookStrategy: "open with a provocative question or scenario", visualDirection: "wide establishing shots, atmospheric" },
      consideration: { toneShift: "informative", messageFrame: "explainer", ctaType: "learn-how", hookStrategy: "state the problem, tease the solution", visualDirection: "diagrams, animations, screen recordings" },
      decision: { toneShift: "persuasive", messageFrame: "testimonial-driven", ctaType: "get-started", hookStrategy: "customer success story opening", visualDirection: "real people, real results footage" },
      retention: { toneShift: "warm", messageFrame: "brand-story", ctaType: "stay-connected", hookStrategy: "nostalgic or emotional opening", visualDirection: "behind-the-scenes, team moments" },
      advocacy: { toneShift: "inspiring", messageFrame: "impact-story", ctaType: "join-the-movement", hookStrategy: "community impact montage", visualDirection: "diverse faces, real-world impact" },
    },
    optimalPublishTimes: { dayOfWeek: [1, 2, 3, 4, 5], hourRange: [9, 17], timezone: "Europe/Amsterdam" },
  },
  {
    platform: "video",
    format: "storyboard",
    specs: { scenes: { min: 4, max: 20 }, sceneDescription: { maxLength: 300 }, visualNotes: { maxLength: 200 } },
    componentTemplate: [
      { type: "scene", required: true, fields: ["sceneNumber", "visualDescription", "dialogue", "duration", "cameraAngle", "transition"] },
      { type: "overall-concept", required: true, maxLength: 500 },
      { type: "mood-board-direction", required: false },
      { type: "music-sound-notes", required: false },
    ],
    bestPractices: [
      "Each scene should serve the narrative — cut anything that doesn't advance the story",
      "Include camera angles and transitions for the production team",
      "Specify audio/music cues per scene for mood consistency",
      "Keep scene descriptions visual — show, don't tell",
      "Include rough timing per scene to hit the target duration",
      "Leave room for improvisation — storyboards are guides, not scripts",
    ],
    phaseGuidance: {
      awareness: { toneShift: "dramatic", messageFrame: "brand-anthem", ctaType: "experience-the-brand", hookStrategy: "opening frame must be visually arresting", visualDirection: "cinematic, wide shots, emotional color grading" },
      consideration: { toneShift: "clear", messageFrame: "product-walkthrough", ctaType: "see-how-it-works", hookStrategy: "problem→solution visual sequence", visualDirection: "clean, well-lit product shots, UI close-ups" },
      decision: { toneShift: "dynamic", messageFrame: "case-study-visual", ctaType: "start-your-journey", hookStrategy: "before/after transformation sequence", visualDirection: "split-screen, progress montage" },
      retention: { toneShift: "intimate", messageFrame: "founder-story", ctaType: "our-mission", hookStrategy: "personal moment or origin story", visualDirection: "close-ups, warm lighting, authentic settings" },
      advocacy: { toneShift: "uplifting", messageFrame: "community-montage", ctaType: "be-part-of-it", hookStrategy: "diverse community members montage", visualDirection: "user-submitted footage, documentary style" },
    },
    optimalPublishTimes: { dayOfWeek: [1, 2, 3, 4, 5], hourRange: [9, 17], timezone: "Europe/Amsterdam" },
  },
  {
    platform: "podcast",
    format: "episode",
    specs: { audioDuration: { min: 600, max: 5400, optimalRange: [1200, 2700] }, maxChars: { title: 100, description: 4000, showNotes: 5000 } },
    componentTemplate: [
      { type: "episode-title", required: true, maxLength: 100 },
      { type: "episode-description", required: true, maxLength: 4000 },
      { type: "intro-script", required: true, maxLength: 500 },
      { type: "segment-outline", required: true },
      { type: "interview-questions", required: false },
      { type: "outro-script", required: true, maxLength: 300 },
      { type: "show-notes", required: true, maxLength: 5000 },
      { type: "chapter-markers", required: false },
    ],
    bestPractices: [
      "Hook listeners in the first 60 seconds — tease the best moment or key insight",
      "Optimal episode length is 20-45 minutes for most audiences",
      "Use consistent intro/outro music for brand recognition",
      "Include chapter markers for podcast apps that support them",
      "Write compelling episode titles — they drive discovery",
      "Show notes should include timestamps, links, and a summary",
      "Publish on a consistent day/time — listeners expect reliability",
      "Include a clear CTA once per episode (subscribe, review, visit site)",
    ],
    phaseGuidance: {
      awareness: { toneShift: "conversational", messageFrame: "trending-topic", ctaType: "subscribe", hookStrategy: "start with the most surprising insight from the episode", visualDirection: "n/a (audio) — use cover art and audiogram clips for promotion" },
      consideration: { toneShift: "expert", messageFrame: "deep-dive", ctaType: "download-resource", hookStrategy: "promise actionable takeaways in the intro", visualDirection: "n/a — promote with quote cards and audiograms" },
      decision: { toneShift: "testimonial", messageFrame: "customer-interview", ctaType: "try-it-yourself", hookStrategy: "customer success story teaser", visualDirection: "n/a — promote with guest headshot and key quote" },
      retention: { toneShift: "intimate", messageFrame: "q-and-a", ctaType: "send-your-questions", hookStrategy: "answer listener questions", visualDirection: "n/a — promote with community engagement post" },
      advocacy: { toneShift: "collaborative", messageFrame: "guest-expert", ctaType: "share-this-episode", hookStrategy: "notable guest introduction with credibility markers", visualDirection: "n/a — promote with guest cross-promotion" },
    },
    optimalPublishTimes: { dayOfWeek: [1, 2, 3], hourRange: [5, 7], timezone: "Europe/Amsterdam" },
  },
  {
    platform: "podcast",
    format: "show-notes",
    specs: { maxChars: { title: 100, summary: 500, fullNotes: 5000 } },
    componentTemplate: [
      { type: "episode-title", required: true, maxLength: 100 },
      { type: "episode-summary", required: true, maxLength: 500 },
      { type: "key-takeaways", required: true },
      { type: "timestamps", required: true },
      { type: "resources-links", required: false },
      { type: "guest-bio", required: false },
      { type: "transcript-excerpt", required: false },
    ],
    bestPractices: [
      "Start with a 2-3 sentence episode summary for SEO and discoverability",
      "List 3-5 key takeaways as bullet points",
      "Include timestamps for every major topic or segment",
      "Link to all resources, tools, and books mentioned in the episode",
      "Include guest social links and a short bio",
      "Add a call-to-action for newsletter, community, or next episode",
      "Repurpose show notes as blog posts for SEO value",
    ],
    phaseGuidance: {
      awareness: { toneShift: "informative", messageFrame: "episode-overview", ctaType: "listen-now", hookStrategy: "highlight the most surprising or valuable takeaway", visualDirection: "n/a — text-based, formatted for podcast apps and web" },
      consideration: { toneShift: "detailed", messageFrame: "resource-companion", ctaType: "get-the-template", hookStrategy: "position show notes as a standalone resource guide", visualDirection: "n/a — use headers and bullet points for scannability" },
      decision: { toneShift: "actionable", messageFrame: "implementation-guide", ctaType: "start-implementing", hookStrategy: "turn episode insights into step-by-step actions", visualDirection: "n/a — numbered lists and action items" },
      retention: { toneShift: "community-focused", messageFrame: "discussion-starter", ctaType: "join-the-conversation", hookStrategy: "pose discussion questions from the episode", visualDirection: "n/a — include community links and discussion prompts" },
      advocacy: { toneShift: "shareable", messageFrame: "quotable-moments", ctaType: "share-this-insight", hookStrategy: "pull the best quotes for social sharing", visualDirection: "n/a — create shareable quote blocks" },
    },
    optimalPublishTimes: { dayOfWeek: [1, 2, 3], hourRange: [5, 7], timezone: "Europe/Amsterdam" },
  },
  {
    platform: "facebook",
    format: "organic-post",
    specs: {
      maxChars: { body: 500, hardLimit: 63206 },
      imageSize: { width: 1200, height: 630 },
      videoMaxDuration: 240,
    },
    componentTemplate: [
      { type: "body", required: true, maxLength: 500 },
      { type: "hashtags", required: false, maxLength: 200 },
      { type: "image", required: false },
    ],
    bestPractices: [
      "Open with a personal hook — a question, confession, or relatable moment; corporate tone underperforms on Facebook",
      "Posts that ask genuine questions get 2-3x more comments — and comment-velocity is the dominant algorithm signal",
      "Keep body 80-250 words — shorter than LinkedIn, more conversational than Instagram",
      "Avoid external links in the post body; put them in the first comment with 'link in comments' instead",
      "Native video posts get ~1.5x more reach than link previews; native photos beat link previews too",
      "1-3 emojis max, used as visual breaks not decoration; more reads as low-quality",
      "End with a specific question (not 'What do you think?') to drive comment threads",
      "Authentic, candid imagery outperforms polished studio shots — Facebook rewards what feels human",
    ],
    phaseGuidance: {
      awareness: { toneShift: "personal", messageFrame: "relatable-story-or-confession", ctaType: "comment-your-take", hookStrategy: "candid moment, contrarian opinion, or 'I almost didn't share this'", visualDirection: "authentic candid photo or behind-the-scenes" },
      consideration: { toneShift: "informative", messageFrame: "tip-or-lesson-learned", ctaType: "save-this-post", hookStrategy: "specific framework or 'here is what I learned'", visualDirection: "infographic, screenshot, or how-to visual" },
      decision: { toneShift: "authentic", messageFrame: "customer-story", ctaType: "dm-or-comment", hookStrategy: "real customer outcome or unexpected interaction", visualDirection: "customer photo, before/after, or unboxing" },
      retention: { toneShift: "celebratory", messageFrame: "community-spotlight", ctaType: "tag-a-friend", hookStrategy: "user win, team milestone, or community moment", visualDirection: "user-generated or team photo" },
      advocacy: { toneShift: "conversational", messageFrame: "discussion-starter", ctaType: "comment-with-yours", hookStrategy: "open question that invites stories", visualDirection: "thought-provoking image or quote-card" },
    },
    optimalPublishTimes: { dayOfWeek: [1, 2, 3, 4, 5], hourRange: [9, 11], timezone: "Europe/Amsterdam" },
  },
  {
    platform: "facebook",
    format: "ad",
    specs: {
      maxChars: { body: 125, headline: 40, description: 30, ctaButton: 25 },
      imageSize: { width: 1200, height: 628 },
      aspectRatio: "1.91:1",
    },
    componentTemplate: [
      { type: "body", required: true, maxLength: 125 },
      { type: "headline", required: true, maxLength: 40 },
      { type: "description", required: false, maxLength: 30 },
      { type: "cta-button", required: true, maxLength: 25 },
      { type: "image", required: true },
    ],
    bestPractices: [
      "Body (primary text) under 125 chars — Meta truncates to ~75 chars on mobile feed with 'See more' fold",
      "Headline 27-40 chars; clear value-proposition, not brand name",
      "CTA button text 2-3 words ('Learn More', 'Shop Now', 'Sign Up'); match Meta's predefined options when possible",
      "1.91:1 image ratio (1200×628) for link-ads; avoid text overlays on image (Meta downranks >20% text-on-image)",
      "Lead body with the hook — primary text first line is the impression-driver",
      "Description (link-description) is optional and often hidden; only fill when it adds unique info",
      "End body with implicit CTA matching the button ('Discover how...' → button 'Learn More')",
    ],
    phaseGuidance: {
      awareness: { toneShift: "curiosity", messageFrame: "problem-snapshot", ctaType: "Learn More", hookStrategy: "pattern-interrupt question or contrarian statement in first line", visualDirection: "single product or moment shot, no text overlay" },
      consideration: { toneShift: "informative", messageFrame: "value-proposition", ctaType: "Get Quote / Download", hookStrategy: "specific outcome ('Cut X by 40%')", visualDirection: "product-in-context or before/after" },
      decision: { toneShift: "decisive", messageFrame: "social-proof-or-offer", ctaType: "Shop Now / Book Now", hookStrategy: "customer quote or limited-time signal", visualDirection: "real customer or product detail" },
      retention: { toneShift: "exclusive", messageFrame: "loyalty-bonus", ctaType: "Get Access", hookStrategy: "subscriber-only benefit", visualDirection: "premium product feature" },
      advocacy: { toneShift: "celebratory", messageFrame: "community-spotlight", ctaType: "Share / Refer", hookStrategy: "user transformation story", visualDirection: "UGC-style customer photo" },
    },
    optimalPublishTimes: { dayOfWeek: [1, 2, 3, 4, 5], hourRange: [9, 11], timezone: "Europe/Amsterdam" },
  },
  {
    platform: "google",
    format: "display-ad",
    // 2026-05-22 — Migrated from legacy 3-fixed-size brief (leaderboard
    // + rectangle + skyscraper) to Google's current 2026-standard
    // Responsive Display Ads (RDA) asset-library paradigm. Google's ML
    // composes assets dynamically into available placements; quantity
    // + diversity of unique assets drive Ad Strength score.
    specs: {
      format: "responsive-display-ad",
      maxChars: { shortHeadline: 30, longHeadline: 90, description: 90, businessName: 25 },
      assetCounts: {
        shortHeadlines: { min: 1, recommended: 5, max: 5 },
        longHeadline: { min: 1, max: 1 },
        descriptions: { min: 1, recommended: 5, max: 5 },
        businessName: { required: true },
      },
      imageAspectRatios: {
        landscape: { ratio: "1.91:1", recommended: "1200x628", minimum: "600x314", required: true },
        square: { ratio: "1:1", recommended: "1200x1200", minimum: "300x300", required: true },
        portrait: { ratio: "4:5", recommended: "1200x1500", minimum: "320x400", required: false },
      },
      logoAspectRatios: {
        square: { ratio: "1:1", recommended: "1200x1200", minimum: "128x128", required: true },
        wide: { ratio: "4:1", recommended: "1200x300", minimum: "512x128", required: false },
      },
      videoSupport: { ratio: "16:9", platform: "YouTube", maxDuration: 30, required: false },
    },
    componentTemplate: [
      // 5 short headlines — Google rotates pairs; diversity > repetition.
      // First is required for Ad Strength minimum; rest optional but
      // filling all 5 drives Ad Strength to Excellent.
      { type: "short-headline-1", required: true, maxLength: 30 },
      { type: "short-headline-2", required: false, maxLength: 30 },
      { type: "short-headline-3", required: false, maxLength: 30 },
      { type: "short-headline-4", required: false, maxLength: 30 },
      { type: "short-headline-5", required: false, maxLength: 30 },
      // Long headline — single, used when ad-placement allows longer text.
      { type: "long-headline", required: true, maxLength: 90 },
      // 5 descriptions — same rotation logic as headlines.
      { type: "description-1", required: true, maxLength: 90 },
      { type: "description-2", required: false, maxLength: 90 },
      { type: "description-3", required: false, maxLength: 90 },
      { type: "description-4", required: false, maxLength: 90 },
      { type: "description-5", required: false, maxLength: 90 },
      // Business name — appears in headers of rendered ads.
      { type: "business-name", required: true, maxLength: 25 },
      // Image marker — visual pipeline produces landscape + square crops.
      { type: "image", required: true },
    ],
    bestPractices: [
      "Provide ALL 5 short headlines + 5 descriptions for 'Excellent' Ad Strength — Google rotates pairs and serves best-performing combos per placement",
      "Each short headline (30 chars) must work standalone AND pair coherently with any other; avoid 'continuation' phrasing that breaks rotation",
      "Long headline (90 chars) shines in placements that allow extended text — make it standalone value-prop, not a longer rephrase of short-headline-1",
      "Descriptions (90 chars each) must add NEW info per slot; duplicates hurt Ad Strength 'diversity' signal",
      "Provide BOTH landscape (1.91:1) AND square (1:1) images — required by Google; add portrait (4:5) for more inventory coverage",
      "Logo: square 1:1 required, wide 4:1 optional but boosts inventory eligibility",
      "<20% text-on-image — Google downranks heavily; copy lives in headlines/descriptions, not baked into images",
      "Business name appears in ad header — use the brand-name exactly as it should appear publicly",
      "Optional YouTube video (≤30s) extends to video-enabled placements; consider for upper-funnel awareness",
    ],
    phaseGuidance: {
      awareness: { toneShift: "curiosity", messageFrame: "pattern-interrupt-or-bold-claim", ctaType: "Learn More", hookStrategy: "varied short-headlines (claim / question / stat / contrarian) to test which lands per placement", visualDirection: "single subject high-contrast in landscape + square; optional portrait for mobile" },
      consideration: { toneShift: "informative", messageFrame: "specific-outcome", ctaType: "Get Quote / See Pricing", hookStrategy: "numeric outcomes ('40% sneller') varied with framework-mentions across the 5 headlines", visualDirection: "product-in-context + result-implication in landscape AND square crops" },
      decision: { toneShift: "decisive", messageFrame: "offer-or-proof", ctaType: "Shop Now / Try Free / Book Demo", hookStrategy: "offer + proof + urgency varied across 5 headlines so Google can A/B test", visualDirection: "product detail + customer-result image" },
      retention: { toneShift: "exclusive", messageFrame: "loyalty-benefit", ctaType: "Get Access / Member-Only", hookStrategy: "5 distinct loyalty-angles for ML rotation", visualDirection: "premium feature highlight in both aspect ratios" },
      advocacy: { toneShift: "celebratory", messageFrame: "user-outcome", ctaType: "Refer & Earn", hookStrategy: "5 different customer-transformation angles", visualDirection: "UGC-style customer photo + brand-mark overlay" },
    },
    optimalPublishTimes: { dayOfWeek: [1, 2, 3, 4, 5], hourRange: [9, 17], timezone: "Europe/Amsterdam" },
  },
  {
    platform: "native",
    format: "sponsored-article",
    specs: {
      maxChars: { headline: 90, subheadline: 140, openingParagraph: 500, body: 2500, brandIntegration: 600, closing: 300, disclosurePosition: 120 },
      targetWordCount: { min: 300, max: 600, sweetSpot: "400-500" },
      brandMentionsMax: 2,
      brandFirstMentionParagraph: 3,
      disclosureRequired: true,
    },
    componentTemplate: [
      { type: "headline", required: true, maxLength: 90 },
      { type: "subheadline", required: false, maxLength: 140 },
      { type: "opening-paragraph", required: true, maxLength: 500 },
      { type: "body", required: true, maxLength: 2500 },
      { type: "brand-integration", required: true, maxLength: 600 },
      { type: "closing", required: true, maxLength: 300 },
      { type: "disclosure-position", required: true, maxLength: 120 },
      { type: "image", required: true },
    ],
    bestPractices: [
      "Headline works as standalone editorial content — clicks must come from curiosity or value, not brand awareness",
      "Bury the brand mention — first reference no earlier than paragraph 3, max 2 mentions in entire article",
      "Opening paragraph delivers pure editorial value (story, stat, observation) with NO brand or product mention",
      "Brand integration emerges naturally ('One platform addressing this...', 'Tools like X have emerged...') — not as hero",
      "Closing is a thought-provoking takeaway or forward-looking statement, NOT a sales pitch",
      "Disclosure tag 'Sponsored by [Brand]' must be in standard byline position (top), legally required (FTC/ASA)",
      "Match publication's tone (BuzzFeed casual vs HBR analytical) — study 5 recent articles before writing",
      "BuzzFeed Principle: content should be shareable even WITHOUT the brand mention; if not, it's not editorial enough",
      "300-600 words optimal (sweet spot 400-500); under 300 = product listing, over 600 = reader drop-off",
      "Use journalism formulas in headlines: How/Why/What + specific outcome, numbered lists, counterintuitive claims, questions",
    ],
    phaseGuidance: {
      awareness: { toneShift: "curious-journalist", messageFrame: "trend-or-observation", ctaType: "natural-recommendation", hookStrategy: "stat + question + contrarian framing in headline", visualDirection: "editorial photo — environment or person-in-context, not product-hero" },
      consideration: { toneShift: "analytical", messageFrame: "framework-or-data-driven", ctaType: "explore-or-discover", hookStrategy: "specific outcome ('Why X% of Y fail') + numbered insights", visualDirection: "diagram, infographic, or analytical photo" },
      decision: { toneShift: "case-study", messageFrame: "real-story-with-data", ctaType: "read-more", hookStrategy: "customer transformation story with hard numbers", visualDirection: "candid customer photo or before/after evidence" },
      retention: { toneShift: "insider", messageFrame: "expert-discussion", ctaType: "join-the-conversation", hookStrategy: "advanced insight or industry-shift observation", visualDirection: "subject-matter expert portrait or community moment" },
      advocacy: { toneShift: "celebratory-but-restrained", messageFrame: "user-driven-story", ctaType: "share-this-insight", hookStrategy: "spotlight customer/community achievement framed as industry trend", visualDirection: "authentic UGC-style photo with editorial composition" },
    },
    optimalPublishTimes: { dayOfWeek: [2, 3, 4], hourRange: [9, 12], timezone: "Europe/Amsterdam" },
  },
  {
    platform: "meta",
    format: "retargeting",
    specs: {
      maxChars: { primaryText: 300, headline: 40, cta: 20, creativeDirection: 250, offerStrategy: 200, frequencyCap: 150 },
      audienceScenarios: ["cart-abandoner", "page-visitor", "past-customer"],
      criticalRule: "Each audience scenario emotional state differs fundamentally; never combine into one ad set",
    },
    componentTemplate: [
      // Cart abandoners — felt desire, hit friction
      { type: "cart-abandoner-primary-text", required: true, maxLength: 300 },
      { type: "cart-abandoner-headline", required: true, maxLength: 40 },
      { type: "cart-abandoner-cta", required: true, maxLength: 20 },
      { type: "cart-abandoner-creative-direction", required: true, maxLength: 250 },
      { type: "cart-abandoner-offer-strategy", required: true, maxLength: 200 },
      { type: "cart-abandoner-frequency-cap", required: true, maxLength: 150 },
      // Page visitors — curious but not convinced
      { type: "page-visitor-primary-text", required: true, maxLength: 300 },
      { type: "page-visitor-headline", required: true, maxLength: 40 },
      { type: "page-visitor-cta", required: true, maxLength: 20 },
      { type: "page-visitor-creative-direction", required: true, maxLength: 250 },
      { type: "page-visitor-offer-strategy", required: true, maxLength: 200 },
      { type: "page-visitor-frequency-cap", required: true, maxLength: 150 },
      // Past customers — trusted you before
      { type: "past-customer-primary-text", required: true, maxLength: 300 },
      { type: "past-customer-headline", required: true, maxLength: 40 },
      { type: "past-customer-cta", required: true, maxLength: 20 },
      { type: "past-customer-creative-direction", required: true, maxLength: 250 },
      { type: "past-customer-offer-strategy", required: true, maxLength: 200 },
      { type: "past-customer-frequency-cap", required: true, maxLength: 150 },
      { type: "image", required: true },
    ],
    bestPractices: [
      "Cart abandoners: address the SPECIFIC friction (price / shipping / trust / distraction), do NOT repeat original value-prop they already saw",
      "Page visitors: provide proof or angle they did NOT see on the page (social proof, FOMO, different framing)",
      "Past customers: NOVELTY + EXPANSION only. NEVER retarget with product they already bought — cross-sell/upsell or new features",
      "Frequency caps are non-negotiable: cart abandoners max 3/day for 3 days then 1/day, page visitors 1/day for 7 days, past customers depends on purchase cycle",
      "Timing: cart abandoners first touch within 1h, page visitors within 24h, past customers per purchase cycle (30d consumables / 90d SaaS / 180d annual)",
      "NEVER combine audience segments in one ad set — different emotional states require different copy/creative/landing pages",
      "NEVER use aggressive urgency ('LAST CHANCE') with cart abandoners — they left for a reason, pressure makes them defensive",
      "NEVER retarget users who opted out / unsubscribed / requested account deletion — privacy regulation violation",
      "Hottest audience gets lightest incentive (past customers don't need a discount); coldest audience may need stronger offer",
    ],
    phaseGuidance: {
      awareness: { toneShift: "curious-not-creepy", messageFrame: "reminder-with-new-angle", ctaType: "Discover Now", hookStrategy: "Reference behavior obliquely + new value-frame they didn't see first time", visualDirection: "Same product/category as visit, but new angle or use-case" },
      consideration: { toneShift: "informative-helpful", messageFrame: "objection-removal-or-proof", ctaType: "Continue Browsing / See How", hookStrategy: "Acknowledge interest + address specific likely-objection", visualDirection: "Demo or social-proof imagery; not pure product-shot" },
      decision: { toneShift: "decisive-friction-removal", messageFrame: "barrier-removal-or-incentive", ctaType: "Complete My Order / Claim Offer", hookStrategy: "Loss-aversion + concrete benefit (free shipping, % off, time-limited)", visualDirection: "Their cart items or hero product with subtle urgency cue (not aggressive)" },
      retention: { toneShift: "warm-novelty-focused", messageFrame: "what-is-new-since-you-last", ctaType: "See What's New", hookStrategy: "Feature update + reciprocity (you saw us first, here's what's new)", visualDirection: "New feature highlight or community moment" },
      advocacy: { toneShift: "exclusive-insider", messageFrame: "early-access-or-refer", ctaType: "Refer Friends / Get Early Access", hookStrategy: "Loyalty-reward + their network as multiplier", visualDirection: "Premium-feel customer photo or VIP-style composition" },
    },
    optimalPublishTimes: { dayOfWeek: [1, 2, 3, 4, 5, 6, 7], hourRange: [8, 22], timezone: "Europe/Amsterdam" },
  },
  {
    platform: "google",
    format: "search-ad",
    specs: {
      maxChars: { headline: 30, description: 90, path: 15, sitelinkTitle: 25, sitelinkDescription: 35 },
      headlines: { min: 3, max: 15, required: 3 },
      descriptions: { min: 2, max: 4, required: 2 },
      sitelinks: { recommended: 4 },
      textOnly: true,
    },
    componentTemplate: [
      { type: "headline-1", required: true, maxLength: 30 },
      { type: "headline-2", required: true, maxLength: 30 },
      { type: "headline-3", required: true, maxLength: 30 },
      { type: "description-1", required: true, maxLength: 90 },
      { type: "description-2", required: true, maxLength: 90 },
      { type: "path-1", required: true, maxLength: 15 },
      { type: "path-2", required: false, maxLength: 15 },
      { type: "sitelink-1-title", required: true, maxLength: 25 },
      { type: "sitelink-1-description", required: true, maxLength: 35 },
      { type: "sitelink-2-title", required: true, maxLength: 25 },
      { type: "sitelink-2-description", required: true, maxLength: 35 },
      { type: "sitelink-3-title", required: true, maxLength: 25 },
      { type: "sitelink-3-description", required: true, maxLength: 35 },
      { type: "sitelink-4-title", required: true, maxLength: 25 },
      { type: "sitelink-4-description", required: true, maxLength: 35 },
    ],
    bestPractices: [
      "Headline 1 = primary keyword + benefit; appears most frequently in rotations",
      "Headline 2 = differentiator, social proof, or urgency trigger",
      "Headline 3 = brand-name, CTA, or trust signal (rotates in alternate combinations)",
      "Each headline must work standalone AND combine well with any other (Google rotates pairs)",
      "Description 1 expands the core benefit + adds proof point",
      "Description 2 adds secondary benefit + specific action CTA (Start / Get / Try / Book)",
      "Display paths are free keyword real-estate — never leave as /page1 /page2",
      "Sitelinks must add new value beyond main ad — restating the title is wasted real estate",
      "No ALL CAPS, no '!' in headlines (Google policy), no unsubstantiated superlatives",
      "Include primary keyword in Headline 1 AND Description 1 for Quality Score",
    ],
    phaseGuidance: {
      awareness: { toneShift: "discovery", messageFrame: "keyword-match", ctaType: "Learn More", hookStrategy: "primary keyword + curiosity-driven benefit in H1", visualDirection: "n/a — text-only ad format" },
      consideration: { toneShift: "informative", messageFrame: "specific-outcome", ctaType: "Get Quote / See Pricing", hookStrategy: "numeric outcome or comparison in H1", visualDirection: "n/a" },
      decision: { toneShift: "urgent", messageFrame: "offer-or-proof", ctaType: "Start Free Trial / Book Demo", hookStrategy: "limited-time signal or social proof in H1+H2", visualDirection: "n/a" },
      retention: { toneShift: "exclusive", messageFrame: "loyalty-benefit", ctaType: "Get Access", hookStrategy: "subscriber-only value", visualDirection: "n/a" },
      advocacy: { toneShift: "celebratory", messageFrame: "user-outcome", ctaType: "Refer & Earn", hookStrategy: "customer transformation snippet", visualDirection: "n/a" },
    },
    optimalPublishTimes: { dayOfWeek: [1, 2, 3, 4, 5], hourRange: [9, 17], timezone: "Europe/Amsterdam" },
  },
  {
    platform: "x",
    format: "thread",
    specs: {
      maxChars: { tweet: 280, premium: 25000 },
      tweetsPerThread: { min: 2, max: 7, sweetSpot: "5-7" },
      media: { imagesPerTweet: 4, videoPerTweet: 1, gifPerTweet: 1 },
    },
    componentTemplate: [
      { type: "hook", required: true, maxLength: 280 },
      { type: "tweet-2", required: false, maxLength: 280 },
      { type: "tweet-3", required: false, maxLength: 280 },
      { type: "tweet-4", required: false, maxLength: 280 },
      { type: "tweet-5", required: false, maxLength: 280 },
      { type: "tweet-6", required: false, maxLength: 280 },
      { type: "cta-tweet", required: false, maxLength: 280 },
      { type: "hashtags", required: false, maxLength: 200 },
    ],
    bestPractices: [
      "Tweet 1 (hook) drives ~90% of impressions — make it standalone-valuable, no 'thread below' teaser",
      "Optimal thread length 5-7 tweets; longer threads drop completion rate",
      "Each tweet must work in isolation — readers may land mid-thread via quote-tweets",
      "Bookmarks > Likes as algorithm signal; write bookmark-worthy content (lists, frameworks, contrarian takes)",
      "End with an explicit CTA tweet (reply, follow, bookmark, or link)",
      "Stay under 280 chars per tweet — no continuation arrows or '1/' numbering inside the text",
      "Use line breaks within tweets for scannability on mobile",
    ],
    phaseGuidance: {
      awareness: { toneShift: "punchy", messageFrame: "contrarian-or-curiosity", ctaType: "follow-for-more", hookStrategy: "bold claim or counterintuitive take in tweet 1", visualDirection: "single image on leader tweet — chart, screenshot, or bold typography" },
      consideration: { toneShift: "educational", messageFrame: "framework-or-listicle", ctaType: "bookmark-this", hookStrategy: "promise specific value ('5 lessons from X')", visualDirection: "diagram or before/after image on leader" },
      decision: { toneShift: "credible", messageFrame: "case-study-or-proof", ctaType: "dm-for-details", hookStrategy: "result-first hook ('We did X, here is how')", visualDirection: "screenshot of results or social proof" },
      retention: { toneShift: "insider", messageFrame: "behind-the-scenes", ctaType: "reply-with-yours", hookStrategy: "share lesson learned or stack reveal", visualDirection: "candid product or workflow shot" },
      advocacy: { toneShift: "celebratory", messageFrame: "user-story", ctaType: "quote-tweet-yours", hookStrategy: "spotlight a customer or community win", visualDirection: "user-generated screenshot or testimonial" },
    },
    optimalPublishTimes: { dayOfWeek: [2, 3, 4], hourRange: [8, 10], timezone: "Europe/Amsterdam" },
  },
];

