// =============================================================
// Brand Kit Bundle (designbibliotheek-verbeterplan W6)
//
// Assembleert de bestaande data tot dezelfde set artefacten die
// Claude Design oplevert (DTS Ede-anatomie): README (mens-digest),
// SKILL.md (agent-manifest), DESIGN.md, tokens.css (werkende CSS met
// @font-face), tokens.json (DTCG), fonts/, assets/, preview/-specimens
// en een toegepaste ui_kit-pagina. Volledig deterministisch — geen
// AI-calls; wat ontbreekt staat eerlijk in Known Gaps (M5).
// =============================================================

import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import JSZip from 'jszip';
import { prisma } from '@/lib/prisma';
import {
  buildBrandManifest,
  renderBrandManifestMarkdown,
  type BrandManifest,
} from '@/lib/brandstyle/manifest-builder';
import type { SemanticTokens } from '@/lib/brandstyle/semantic-role-resolver';
import {
  renderColorSpecimenHtml,
  renderTypeSpecimenHtml,
  renderUiKitHtml,
  type SpecimenFixtures,
} from '@/lib/brandstyle/specimens';
import { buildDesignSystemModel } from '@/lib/export/design-system/resolver';
import { emitDesignMd } from '@/lib/export/design-system/emitters/designmd';
import { emitDtcg } from '@/lib/export/design-system/emitters/dtcg';

export interface BrandKitBundleResult {
  zip: Uint8Array;
  manifestVersion: number;
  /** Bestanden die niet opgehaald konden worden — eerlijk gerapporteerd. */
  missingFiles: string[];
}

/** Haal een asset op: lokale /uploads-paden van disk, anders via fetch. */
async function loadAsset(fileUrl: string): Promise<Uint8Array | null> {
  try {
    if (fileUrl.startsWith('/')) {
      const path = join(process.cwd(), 'public', fileUrl);
      return new Uint8Array(await readFile(path));
    }
    const res = await fetch(fileUrl);
    if (!res.ok) return null;
    return new Uint8Array(await res.arrayBuffer());
  } catch {
    return null;
  }
}

function fileBasename(fileUrl: string, fallback: string): string {
  const clean = fileUrl.split('?')[0];
  const base = clean.substring(clean.lastIndexOf('/') + 1);
  return base.length > 0 ? base : fallback;
}

/** Werkende stylesheet: raw semantic rollen als CSS-vars + @font-face-ladder. */
function buildTokensCss(
  manifest: BrandManifest,
  fontFiles: Array<{ family: string; weight: string | null; path: string }>,
): string {
  const lines: string[] = [
    '/* Generated by Branddock — Brand Kit Bundle */',
    `/* ${manifest.brandName} · manifest v${manifest.manifestVersion} */`,
    '',
  ];
  for (const font of fontFiles) {
    lines.push('@font-face {');
    lines.push(`  font-family: "${font.family}";`);
    lines.push(`  src: url("${font.path}");`);
    if (font.weight) lines.push(`  font-weight: ${font.weight};`);
    lines.push('  font-display: swap;');
    lines.push('}');
    lines.push('');
  }
  lines.push(':root {');
  for (const [role, hex] of Object.entries(manifest.tokens?.colors ?? {})) {
    lines.push(`  --color-${role}: ${hex};`);
  }
  for (const [name, px] of Object.entries(manifest.tokens?.spacing ?? {})) {
    lines.push(`  --spacing-${name}: ${px}px;`);
  }
  for (const [name, px] of Object.entries(manifest.tokens?.rounded ?? {})) {
    lines.push(`  --rounded-${name}: ${px}px;`);
  }
  for (const [level, shadow] of Object.entries(manifest.tokens?.elevation ?? {})) {
    lines.push(`  --elevation-${level}: ${shadow};`);
  }
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

/** SKILL.md — het agent-manifest in Claude-skill-vorm (DTS-patroon). */
function buildSkillMd(manifest: BrandManifest, markdown: string): string {
  const slug = manifest.brandName.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  return `---
name: ${slug}-brand
description: Use this skill to generate well-branded interfaces, content and assets for ${manifest.brandName}. Contains the curated brand manifest — quick facts, hard rules, semantic tokens, voice baseline and known gaps.
user-invocable: true
---

Read this manifest before producing anything for ${manifest.brandName}. Copy assets
from \`assets/\` and \`fonts/\`, use \`tokens.css\` for working styles, and treat the
rules below as constraints — BLOCKING rules must never be violated.

${markdown}
`;
}

/** README.md — mens-digest: manifest + leeswijzer + bundelinhoud. */
function buildReadme(manifest: BrandManifest, markdown: string, missingFiles: string[]): string {
  const missing =
    missingFiles.length > 0
      ? `\n## Missing files\n\nThese source files could not be bundled (not uploaded or unreachable):\n${missingFiles.map((f) => `- ${f}`).join('\n')}\n`
      : '';
  return `${markdown}

---

## About this bundle

Generated by Branddock from the live brand library (manifest v${manifest.manifestVersion}).

\`\`\`
README.md     ← this digest (humans)
SKILL.md      ← agent manifest (drop into an AI coding/design agent)
DESIGN.md     ← token + component reference (Stitch/DESIGN.md format)
tokens.css    ← working stylesheet: semantic CSS variables + @font-face
tokens.json   ← W3C DTCG design tokens
fonts/        ← brand font files (when uploaded)
assets/       ← logo files
preview/      ← specimen cards (colors, typography)
ui_kit/       ← the brand applied to a real sample page
\`\`\`
${missing}`;
}

/** DESIGN.md-aanvulling: Iteration Guide + Known Gaps (§1.3 M6). */
function appendDesignMdSections(designMd: string, manifest: BrandManifest): string {
  const parts: string[] = [designMd.trimEnd(), ''];
  parts.push('## Iteration Guide');
  parts.push('');
  for (const item of manifest.iterationGuide) parts.push(`- ${item}`);
  parts.push('');
  parts.push('## Known Gaps');
  parts.push('');
  if (manifest.knownGaps.length === 0) {
    parts.push('- None recorded — extraction looks complete.');
  } else {
    for (const gap of manifest.knownGaps) parts.push(`- ${gap}`);
  }
  parts.push('');
  return parts.join('\n');
}

/**
 * Bouw de complete Brand Kit Bundle voor een workspace. Gebruikt het
 * opgeslagen manifest wanneer aanwezig; anders een verse deterministische
 * build (zonder persist — de bundle mag de bibliotheek niet muteren).
 */
export async function buildBrandKitBundle(workspaceId: string): Promise<BrandKitBundleResult | null> {
  const [styleguide, voiceguide, workspace] = await Promise.all([
    prisma.brandStyleguide.findUnique({
      where: { workspaceId },
      include: { colors: true, fonts: true, logos: true, rules: true },
    }),
    prisma.brandVoiceguide.findUnique({ where: { workspaceId } }),
    prisma.workspace.findUnique({ where: { id: workspaceId }, select: { name: true } }),
  ]);
  if (!styleguide) return null;

  const brandName = workspace?.name ?? 'Brand';
  const manifest =
    (styleguide.brandManifest as unknown as BrandManifest | null) ??
    buildBrandManifest(styleguide, voiceguide, brandName);
  const markdown = renderBrandManifestMarkdown(manifest);

  const zip = new JSZip();
  const missingFiles: string[] = [];

  // Fonts + assets (best effort, eerlijk over wat mist)
  const fontFiles: Array<{ family: string; weight: string | null; path: string }> = [];
  for (const font of styleguide.fonts) {
    if (!font.fileUrl) {
      if (font.source === 'UPLOADED') missingFiles.push(`fonts/${font.name} (no file URL)`);
      continue;
    }
    const bytes = await loadAsset(font.fileUrl);
    const name = fileBasename(font.fileUrl, `${font.name}.font`);
    if (bytes) {
      zip.file(`fonts/${name}`, bytes);
      fontFiles.push({
        family: font.fontFamily ?? font.name,
        weight: font.weight,
        path: `fonts/${name}`,
      });
    } else {
      missingFiles.push(`fonts/${name}`);
    }
  }
  for (const logo of styleguide.logos) {
    if (!logo.fileUrl) continue;
    const bytes = await loadAsset(logo.fileUrl);
    const name = fileBasename(logo.fileUrl, `${logo.variant.toLowerCase()}.png`);
    if (bytes) {
      zip.file(`assets/${name}`, bytes);
    } else {
      missingFiles.push(`assets/${name}`);
    }
  }

  // Documenten
  const model = await buildDesignSystemModel(workspaceId);
  zip.file('README.md', buildReadme(manifest, markdown, missingFiles));
  zip.file('SKILL.md', buildSkillMd(manifest, markdown));
  zip.file('DESIGN.md', appendDesignMdSections(emitDesignMd(model), manifest));
  zip.file('tokens.json', JSON.stringify(emitDtcg(model), null, 2));
  zip.file('tokens.css', buildTokensCss(manifest, fontFiles));

  // Specimens + toegepaste kit
  const semantic = styleguide.semanticTokens as SemanticTokens | null;
  const specimenInput = {
    brandName,
    tokens: semantic?.resolved ? { ...semantic.resolved, ...(semantic.overrides ?? {}) } : null,
    primaryFontName: styleguide.primaryFontName,
    fixtures: (styleguide.fixtureSamples as SpecimenFixtures | null) ?? null,
  };
  zip.file('preview/colors.html', renderColorSpecimenHtml(specimenInput));
  zip.file('preview/typography.html', renderTypeSpecimenHtml(specimenInput));
  zip.file('ui_kit/index.html', renderUiKitHtml(specimenInput));

  const bytes = await zip.generateAsync({ type: 'uint8array', compression: 'DEFLATE' });
  return { zip: bytes, manifestVersion: manifest.manifestVersion, missingFiles };
}
