import { z } from "zod";

export const createPersonaSchema = z.object({
  name: z.string().min(1, "Name is required").max(255),
  tagline: z.string().max(500).optional(),
  role: z.string().max(255).optional(),
  description: z.string().max(5000).optional(),
  avatar: z.string().url().optional().nullable(),
  imageUrl: z.string().url().optional().nullable(),
  age: z.string().max(50).optional(),
  gender: z.string().max(50).optional(),
  location: z.string().max(255).optional(),
  occupation: z.string().max(255).optional(),
  education: z.string().max(255).optional(),
  income: z.string().max(255).optional(),
  familyStatus: z.string().max(255).optional(),
  personalityType: z.string().max(100).optional(),
  coreValues: z.array(z.string()).optional(),
  interests: z.array(z.string()).optional(),
  goals: z.array(z.unknown()).optional(),
  motivations: z.array(z.unknown()).optional(),
  frustrations: z.array(z.unknown()).optional(),
  painPoints: z.array(z.unknown()).optional(),
  behaviors: z.array(z.unknown()).optional(),
  tags: z.array(z.string()).optional(),
  workspaceId: z.string().uuid("Invalid workspace ID"),
});

export const updatePersonaSchema = z.object({
  name: z.string().min(1).max(255).optional(),
  tagline: z.string().max(500).optional().nullable(),
  role: z.string().max(255).optional().nullable(),
  description: z.string().max(5000).optional().nullable(),
  avatar: z.string().url().optional().nullable(),
  imageUrl: z.string().url().optional().nullable(),
  researchConfidence: z.number().min(0).max(100).optional(),
  methodsCompleted: z.number().int().min(0).optional(),
  age: z.string().max(50).optional().nullable(),
  gender: z.string().max(50).optional().nullable(),
  location: z.string().max(255).optional().nullable(),
  occupation: z.string().max(255).optional().nullable(),
  education: z.string().max(255).optional().nullable(),
  income: z.string().max(255).optional().nullable(),
  familyStatus: z.string().max(255).optional().nullable(),
  personalityType: z.string().max(100).optional().nullable(),
  coreValues: z.array(z.string()).optional().nullable(),
  interests: z.array(z.string()).optional().nullable(),
  goals: z.array(z.unknown()).optional().nullable(),
  motivations: z.array(z.unknown()).optional().nullable(),
  frustrations: z.array(z.unknown()).optional().nullable(),
  painPoints: z.array(z.unknown()).optional().nullable(),
  behaviors: z.array(z.unknown()).optional().nullable(),
  strategicImplications: z.array(z.unknown()).optional().nullable(),
  demographics: z.record(z.string(), z.unknown()).optional().nullable(),
  tags: z.array(z.string()).optional().nullable(),
});

export type CreatePersonaInput = z.infer<typeof createPersonaSchema>;
export type UpdatePersonaInput = z.infer<typeof updatePersonaSchema>;
