import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { resolveWorkspaceId, getServerSession } from "@/lib/auth-server";

// POST /api/personas/[id]/chat/[sessionId]/message
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string; sessionId: string }> }
) {
  try {
    const workspaceId = await resolveWorkspaceId();
    if (!workspaceId) {
      return NextResponse.json({ error: "No workspace found" }, { status: 403 });
    }

    await getServerSession();

    const { id, sessionId } = await params;

    // Verify persona exists in workspace
    const persona = await prisma.persona.findFirst({
      where: { id, workspaceId },
    });
    if (!persona) {
      return NextResponse.json({ error: "Persona not found" }, { status: 404 });
    }

    // Verify session belongs to this persona
    const chatSession = await prisma.personaChatSession.findFirst({
      where: { id: sessionId, personaId: id },
    });
    if (!chatSession) {
      return NextResponse.json({ error: "Chat session not found" }, { status: 404 });
    }

    const body = await request.json();
    const { content } = body;

    if (!content || typeof content !== "string") {
      return NextResponse.json(
        { error: "content is required and must be a string" },
        { status: 400 }
      );
    }

    // Save user message
    const userMessage = await prisma.personaChatMessage.create({
      data: {
        role: "USER",
        content,
        sessionId,
      },
    });

    // Generate stub AI response
    const name = persona.name;
    const occupation = persona.occupation || "a professional";
    const location = persona.location || "my area";
    const firstCoreValue =
      persona.coreValues && persona.coreValues.length > 0
        ? persona.coreValues[0]
        : "quality";

    const paraphrase =
      content.length > 50
        ? "That's a complex topic that deserves careful consideration."
        : "I appreciate you bringing that up.";

    const assistantContent = `As ${name}, ${occupation} from ${location}, I think that's an interesting point. ${paraphrase} Given my focus on ${firstCoreValue}, I'd say this is worth considering carefully.`;

    // Save assistant message
    const assistantMessage = await prisma.personaChatMessage.create({
      data: {
        role: "ASSISTANT",
        content: assistantContent,
        sessionId,
      },
    });

    // Check if this is every 3rd user message — generate an insight
    const userMessageCount = await prisma.personaChatMessage.count({
      where: { sessionId, role: "USER" },
    });

    let newInsights: Array<{
      id: string;
      type: string;
      title: string;
      content: string;
      severity: string | null;
      isAutoGenerated: boolean;
      messageId: string | null;
      createdAt: string;
    }> = [];

    if (userMessageCount % 3 === 0) {
      const insight = await prisma.personaChatInsight.create({
        data: {
          title: "Insight from conversation",
          content: `Based on ${name}'s perspective, this conversation has revealed important patterns about their decision-making process and priorities.`,
          type: "behavior",
          severity: "medium",
          isAutoGenerated: true,
          messageId: assistantMessage.id,
          sessionId,
        },
      });

      newInsights = [
        {
          id: insight.id,
          type: insight.type,
          title: insight.title,
          content: insight.content,
          severity: insight.severity,
          isAutoGenerated: insight.isAutoGenerated,
          messageId: insight.messageId,
          createdAt: insight.createdAt.toISOString(),
        },
      ];
    }

    const response: Record<string, unknown> = {
      reply: {
        id: assistantMessage.id,
        role: assistantMessage.role,
        content: assistantMessage.content,
        createdAt: assistantMessage.createdAt.toISOString(),
      },
    };

    if (newInsights.length > 0) {
      response.insights = newInsights;
    }

    // Include userMessage for reference
    response.userMessage = {
      id: userMessage.id,
      role: userMessage.role,
      content: userMessage.content,
      createdAt: userMessage.createdAt.toISOString(),
    };

    return NextResponse.json(response);
  } catch (error) {
    console.error("[POST /api/personas/:id/chat/:sessionId/message]", error);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
