import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { resolveWorkspaceId } from "@/lib/auth-server";

// ─── GET /api/personas/[id]/chat/[sessionId] ─────────────────
// Retrieve a chat session with all its messages
// ──────────────────────────────────────────────────────────────
export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string; sessionId: string }> }
) {
  try {
    const workspaceId = await resolveWorkspaceId();
    if (!workspaceId) {
      return NextResponse.json({ error: "No workspace found" }, { status: 403 });
    }

    const { id: personaId, sessionId } = await params;

    // Verify persona exists in workspace
    const persona = await prisma.persona.findFirst({
      where: { id: personaId, workspaceId },
      select: { id: true },
    });
    if (!persona) {
      return NextResponse.json({ error: "Persona not found" }, { status: 404 });
    }

    // Fetch session with messages and insights
    const chatSession = await prisma.personaChatSession.findFirst({
      where: { id: sessionId, personaId, workspaceId },
      include: {
        messages: {
          orderBy: { createdAt: "asc" },
          select: {
            id: true,
            role: true,
            content: true,
            promptTokens: true,
            completionTokens: true,
            createdAt: true,
          },
        },
        insights: {
          orderBy: { createdAt: "desc" },
          select: {
            id: true,
            type: true,
            title: true,
            content: true,
            severity: true,
            messageId: true,
            isAutoGenerated: true,
            createdAt: true,
          },
        },
        knowledgeContext: {
          orderBy: { createdAt: "asc" },
          select: {
            id: true,
            sourceType: true,
            sourceId: true,
            sourceName: true,
            createdAt: true,
          },
        },
      },
    });

    if (!chatSession) {
      return NextResponse.json({ error: "Chat session not found" }, { status: 404 });
    }

    return NextResponse.json({
      id: chatSession.id,
      mode: chatSession.mode,
      title: chatSession.title,
      createdAt: chatSession.createdAt.toISOString(),
      updatedAt: chatSession.updatedAt.toISOString(),
      messages: chatSession.messages.map((m) => ({
        id: m.id,
        role: m.role,
        content: m.content,
        promptTokens: m.promptTokens,
        completionTokens: m.completionTokens,
        createdAt: m.createdAt.toISOString(),
      })),
      insights: chatSession.insights.map((i) => ({
        id: i.id,
        type: i.type,
        title: i.title,
        content: i.content,
        severity: i.severity,
        messageId: i.messageId,
        isAutoGenerated: i.isAutoGenerated,
        createdAt: i.createdAt.toISOString(),
      })),
      knowledgeContext: chatSession.knowledgeContext.map((c) => ({
        id: c.id,
        sourceType: c.sourceType,
        sourceId: c.sourceId,
        sourceName: c.sourceName,
        createdAt: c.createdAt.toISOString(),
      })),
    });
  } catch (error) {
    console.error("[GET /api/personas/:id/chat/:sessionId]", error);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
