export type ChatRole = 'USER' | 'ASSISTANT' | 'SYSTEM';

export interface ChatSession {
  id: string;
  mode: string;
  title: string | null;
  messages: ChatMessage[];
  insights: ChatInsight[];
  knowledgeContext: ChatContext[];
  createdAt: string;
}

export interface ChatMessage {
  id: string;
  role: ChatRole;
  content: string;
  promptTokens?: number | null;
  completionTokens?: number | null;
  createdAt: string;
}

export interface ChatInsight {
  id: string;
  sessionId: string;
  messageId: string | null;
  type: string;
  title: string;
  content: string;
  severity: string | null;
  isAutoGenerated: boolean;
  createdAt: string;
}

export interface ChatContext {
  id: string;
  sessionId: string;
  sourceType: string;
  sourceId: string;
  sourceName: string;
  contextData: Record<string, unknown>;
  createdAt: string;
}

export interface ChatConfig {
  id: string;
  workspaceId: string;
  provider: string;
  model: string;
  temperature: number;
  maxTokens: number;
  systemPromptTemplate: string;
}

export interface SendMessageBody {
  content: string;
  sessionId?: string;
  knowledgeContextIds?: {
    sourceType: string;
    sourceId: string;
  }[];
}
