// Render-edge i18n catalog for the content-type-inputs registry (nl).
// AUTOGENERATED — source of truth: src/features/campaigns/lib/content-type-inputs.ts (English strings).
// Keyed on the registry's stable field `key` (+ per-type overrides where the same key
// carries a different English string). Do not hand-edit; regenerate from the registry.
const ns = {
  "categories": {
    "conversion-hook": "Conversiehook",
    "authority-frame": "Autoriteitsframe",
    "narrative-anchor": "Narratief anker",
    "structure-skeleton": "Structuurskelet",
    "seo": "SEO & zoekwoorden",
    "content-style": "Contentstijl",
    "engagement": "Engagement",
    "campaign-details": "Campagnedetails",
    "format-specs": "Formaat & specs",
    "audience": "Doelgroep",
    "references": "Referenties & bronnen",
    "creative-direction": "Creatieve richting"
  },
  "tone": {
    "professional": "Professioneel",
    "casual": "Casual",
    "inspirational": "Inspirerend",
    "educational": "Educatief",
    "humorous": "Humoristisch",
    "authoritative": "Gezaghebbend",
    "conversational": "Conversationeel",
    "analytical": "Analytisch",
    "journalistic": "Journalistiek",
    "consultative": "Adviserend",
    "direct": "Direct",
    "premium": "Premium",
    "friendly": "Vriendelijk",
    "neutral-journalistic": "Neutraal / journalistiek",
    "official": "Officieel",
    "warm-personal": "Warm / persoonlijk",
    "advocacy": "Pleitbezorgend",
    "urgent": "Urgent",
    "playful": "Speels",
    "bold": "Gedurfd",
    "aspirational": "Aspirerend",
    "energetic": "Energiek",
    "cinematic": "Cinematisch"
  },
  "cta": {
    "Direct": "Directe vraag",
    "Question": "Vraag om te betrekken",
    "Soft suggestion": "Zachte suggestie",
    "Request a demo": "Vraag een demo aan",
    "Book a meeting": "Plan een gesprek",
    "Start free trial": "Start gratis proefperiode",
    "Contact sales": "Neem contact op met sales"
  },
  "fields": {
    "uniqueAngle": {
      "label": "Unieke invalshoek",
      "placeholder": "bijv. \"De meeste positioneringsframeworks falen omdat ze positionering als creatief in plaats van operationeel behandelen\"",
      "help": "Wat deze content zegt dat 95% van de rest niet zegt — 1-2 zinnen"
    },
    "evidencePieces": {
      "label": "Bewijsstukken",
      "placeholder": "Eén bewijsstuk per regel:\n- Reichheld churn-data 2024\n- Patagonia-case (Worn Wear)\n- Eigen voice-fidelity-benchmark (n=200)",
      "help": "Eén bewijsstuk per regel — minimaal 3, maximaal 7 (quotes, statistieken, klantvoorbeelden, anekdotes)"
    },
    "counterClaim": {
      "label": "Tegenclaim (optioneel)",
      "placeholder": "bijv. \"Positionering is een constraint-engineering-probleem, geen creatieve oefening\"",
      "help": "De antithese die de content expliciet weerlegt — scherpt het argument aan"
    },
    "articleStructure": {
      "label": "Artikelstructuur",
      "help": "Hoe het artikel is opgebouwd"
    },
    "includeFaq": {
      "label": "FAQ-sectie toevoegen",
      "help": "Genereer een FAQ-blok aan het eind — handig voor SEO"
    },
    "seoKeyword": {
      "label": "SEO-zoekwoord",
      "placeholder": "bijv. merkpositioneringsstrategie",
      "help": "Primair zoekwoord om op te ranken"
    },
    "secondaryKeywords": {
      "label": "Secundaire zoekwoorden",
      "placeholder": "Zoekwoord toevoegen…",
      "help": "Gerelateerde zoekwoorden om natuurlijk te verwerken"
    },
    "metaDescription": {
      "label": "Meta-omschrijving",
      "placeholder": "SEO-meta-omschrijving van 150-160 tekens",
      "help": "Snippet in het zoekresultaat"
    },
    "internalLinks": {
      "label": "Interne links om op te nemen",
      "placeholder": "Pagina/onderwerp om naar te linken toevoegen…",
      "help": "Pagina's of onderwerpen om naar te verwijzen"
    },
    "optimizationGoals": {
      "label": "Optimalisatiedoel",
      "help": "SEO draait de zoekmachine-pipeline; GEO genereert een citeerbaar artikel voor AI-antwoordmachines. Uitvinken slaat dat doel over."
    },
    "structure": {
      "label": "Structuur"
    },
    "quoteCount": {
      "label": "Ingebedde quotes (0–4)",
      "placeholder": "2",
      "help": "Aantal quote-placeholders om te genereren"
    },
    "includeBoilerplate": {
      "label": "Boilerplate toevoegen",
      "help": "Standaard \"Over [merk]\"-blok aan het eind"
    },
    "includeContactBlock": {
      "label": "Perscontact toevoegen",
      "help": "Naam- / e-mail- / telefoon-placeholders voor media"
    },
    "jobTitle": {
      "label": "Functietitel",
      "placeholder": "bijv. Senior Brand Strategist",
      "help": "Functietitel"
    },
    "jobLocation": {
      "label": "Locatie",
      "placeholder": "bijv. Amsterdam, Nederland (hybride)",
      "help": "Werklocatie en thuiswerkbeleid"
    },
    "salaryRange": {
      "label": "Salarisrange",
      "placeholder": "bijv. €60.000 - €80.000",
      "help": "Salarisindicatie (aanbevolen voor transparantie)"
    },
    "whyNowAngle": {
      "label": "Waarom nu",
      "placeholder": "bijv. \"Nu de EU AI Act vanaf Q1 2026 van kracht is, moeten merkteams hun audit trail voor AI-content kunnen aantonen\"",
      "help": "Wat dit NU nieuwswaardig maakt — de journalistieke timing-hook"
    },
    "pivotMoment": {
      "label": "Kantelmoment",
      "placeholder": "bijv. \"het moment waarop de klant durfde zijn team te halveren\"",
      "help": "Het narratieve scharnier — de specifieke scène waar het verhaal om draait"
    },
    "industryContext": {
      "label": "Branchecontext (optioneel)",
      "placeholder": "bijv. \"in een markt waar 80% van de AI-tools nog uitsluitend Engelstalige output geeft\"",
      "help": "Bredere branchecontext waarin het verhaal staat (optioneel)"
    },
    "solutionPhases": {
      "label": "Oplossingsfases (3-5)",
      "placeholder": "Eén implementatiefase per regel:\n- Discovery + audit (week 1-2)\n- Voice-baseline definiëren (week 3)\n- Team-uitrol (week 4-6)",
      "help": "3-5 implementatiestappen — geeft de case study ruggengraat en tempo"
    },
    "failureFootnote": {
      "label": "Faalvoetnoot (optioneel maar geloofwaardig)",
      "placeholder": "bijv. \"Eerste poging gestrand: voice-guide te abstract; iteratie 2 voegde concrete do/don't-voorbeelden toe\"",
      "help": "Wat er onderweg misging — voegt geloofwaardigheid toe, doorbreekt het heiligenpatroon"
    },
    "customerName": {
      "label": "Klant- / bedrijfsnaam",
      "placeholder": "bijv. Acme Corp",
      "help": "De uitgelichte klant (gebruik een placeholder als het vertrouwelijk is)"
    },
    "challengeDescription": {
      "label": "Omschrijving uitdaging",
      "placeholder": "Welk probleem had de klant?",
      "help": "De zakelijke uitdaging vóór jouw oplossing"
    },
    "keyMetrics": {
      "label": "Belangrijkste resultaten / cijfers",
      "placeholder": "bijv. +40% omzet, 2x conversieratio",
      "help": "Kwantificeerbare resultaten om uit te lichten"
    },
    "customerQuote": {
      "label": "Klantquote",
      "placeholder": "Een testimonial-quote van de klant",
      "help": "Directe quote voor social proof"
    },
    "differentiatorClaim": {
      "label": "Onderscheidende claim",
      "placeholder": "bijv. \"Wij meten brand voice; concurrenten meten alleen visuele consistentie\"",
      "help": "1 zin die de ene dimensie benoemt waarop je wint — verankert de vergelijking"
    },
    "tonePosition": {
      "label": "Toonpositie",
      "help": "Vergelijkingstoon — te agressief werkt averechts, te zacht is verspilde moeite"
    },
    "seoFocus": {
      "label": "SEO-focus",
      "help": "Optimaliseer koppen en meta voor zoekmachines"
    },
    "competitors": {
      "label": "Concurrenten om te vergelijken",
      "placeholder": "Concurrentnaam toevoegen…",
      "help": "Met welke concurrenten je vergelijkt"
    },
    "comparisonCriteria": {
      "label": "Vergelijkingscriteria",
      "placeholder": "bijv. Prijs, Functies, Support, Integraties",
      "help": "Dimensies om op te vergelijken"
    },
    "hookFormat": {
      "label": "Hookformaat",
      "help": "Stuurt de eerste 1–3 regels / openingsseconden"
    },
    "payoffPromise": {
      "label": "Payoff-belofte",
      "placeholder": "bijv. \"Een 3-stappen-frame om brand-fluff te detecteren\"",
      "help": "Wat de lezer krijgt als hij doorleest / doorklikt"
    },
    "targetObjection": {
      "label": "Doel-bezwaar",
      "placeholder": "bijv. \"marketing-budget al uitgeput\"",
      "help": "Concrete weerstand die de copy direct moet adresseren (optioneel)"
    },
    "proofPoint": {
      "label": "Bewijspunt",
      "placeholder": "bijv. \"Better Brands +24% voice-fidelity in 4 weken\"",
      "help": "1 cijfer / quote / klantfragment voor de body (optioneel)"
    },
    "valueProposition": {
      "label": "Waardepropositie",
      "placeholder": "bijv. \"Voor brand-managers die voice-consistency willen meten — zonder eigen taal-team op te bouwen\"",
      "help": "Korte, scherpe waardepropositie waarop de advertentiecopy ankert"
    },
    "headlineCount": {
      "label": "Kopvarianten (standaard 2)",
      "placeholder": "2",
      "help": "Aantal kopvariaties om te genereren (best practice Google search-ad-asset: 3-5)"
    },
    "ctaType": {
      "label": "CTA-type"
    },
    "socialProof": {
      "label": "Social proof toevoegen",
      "help": "Voeg een testimonial of cijfer toe aan de advertentiecopy"
    },
    "landingPageUrl": {
      "label": "Landingspagina-URL",
      "placeholder": "bijv. https://example.com/aanbod",
      "help": "Waar de CTA naartoe moet linken"
    },
    "dominantVisualElement": {
      "label": "Dominant visueel element",
      "placeholder": "bijv. \"product hero shot in het midden, gedurfde contrast-badge rechtsboven\"",
      "help": "Display-ads hebben ruimte voor ~1-2 woorden copy — visuele focus is essentieel"
    },
    "cultureSignal": {
      "label": "Cultuursignaal",
      "placeholder": "bijv. \"team durft elkaar te corrigeren in design-review zonder hiërarchie\"",
      "help": "1 specifiek cultuurgedrag dat het verhaal impliciet toont"
    },
    "employeeName": {
      "label": "Naam & functie medewerker",
      "placeholder": "bijv. Maria Santos, Lead Designer — 3 jaar bij het bedrijf",
      "help": "Details van de uitgelichte medewerker"
    },
    "storyAngle": {
      "label": "Verhaal-invalshoek",
      "help": "Verhalende focus van het verhaal"
    },
    "footageType": {
      "label": "Type beeldmateriaal"
    },
    "textOverlay": {
      "label": "Tekstoverlay",
      "help": "Stijl van on-screen tekst — stuurt het ondertitelritme en de visuele dichtheid"
    },
    "colorGrade": {
      "label": "Kleurgradatie",
      "help": "Visuele sfeer — beïnvloedt phrasing en toon (warm = nostalgisch, koel = professioneel, levendig = energiek, natuurlijk = documentaire)"
    },
    "videoDuration": {
      "label": "Duur (seconden)",
      "placeholder": "bijv. 30",
      "help": "Doelduur van video/audio in seconden"
    },
    "sceneSkeleton": {
      "label": "Scèneskelet",
      "placeholder": "Eén scène per regel:\n- Het probleem dat niemand benoemt\n- De data die het bewijst\n- Onze aanpak\n- Bewijs uit een klantcase\n- De volgende stap",
      "help": "Eén scène per regel — 1-op-1 gebruikt als scènetitel. Optioneel: `Titel — bullet1; bullet2` voor subpunten."
    },
    "sceneHook": {
      "label": "Hook openingsscène",
      "placeholder": "bijv. \"De meeste merken meten hun brand voice niet — wij wel.\"",
      "help": "Exacte openingsregel voor scène 1 (of het geheel). Doorslaggevend voor engagement."
    },
    "payoffPosition": {
      "label": "Payoff-scène (nummer)",
      "placeholder": "4",
      "help": "Welk scènenummer levert de payoff (meestal op 60-70% van het geheel)."
    },
    "coreAnalogy": {
      "label": "Kernanalogie",
      "placeholder": "bijv. \"brand-voice-consistentie = een stemtest in een koor — mis één partij en het valt op\"",
      "help": "De ene metafoor waar de explainer op leunt — explainers staan of vallen hiermee"
    },
    "videoFormat": {
      "label": "Videoformaat",
      "help": "Productiestijl van de explainer"
    },
    "complexityLevel": {
      "label": "Complexiteit onderwerp",
      "help": "Bepaalt uitlegdiepte en jargonniveau"
    },
    "hashtagStrategy": {
      "label": "Hashtag-strategie",
      "help": "Welk soort hashtags je aan het eind van de post toevoegt"
    },
    "includeEmoji": {
      "label": "Emoji's toevoegen",
      "help": "Verweef emoji's natuurlijk in de posttekst"
    },
    "postType": {
      "label": "Posttype",
      "help": "Postformaat bepaalt de engagementstijl"
    },
    "audienceMood": {
      "label": "Stemming doelgroep",
      "help": "Facebook is conversationeel — stemming-input verschuift de toon aanzienlijk"
    },
    "topQuestions": {
      "label": "Belangrijkste vragen om te beantwoorden",
      "placeholder": "Vraag toevoegen…",
      "help": "Meest gestelde klantvragen"
    },
    "reportingPeriod": {
      "label": "Rapportageperiode",
      "placeholder": "bijv. FY 2025, Q1-Q2 2026",
      "help": "Periode die het rapport beslaat"
    },
    "impactMetrics": {
      "label": "Belangrijkste impactcijfers",
      "placeholder": "bijv. CO2 40% omlaag, 500 banen gecreëerd, €2M gedoneerd",
      "help": "Kwantificeerbare impactdata om uit te lichten"
    },
    "stakeholderAudience": {
      "label": "Primaire doelgroep",
      "help": "Wie dit rapport gaat lezen"
    },
    "esgFramework": {
      "label": "Rapportageframework",
      "help": "Gebruikt ESG- / duurzaamheidsrapportageframework"
    },
    "captionLength": {
      "label": "Bijschriftlengte",
      "help": "Bepaalt de diepte en structuur van het bijschrift"
    },
    "firstLineMagnet": {
      "label": "Eersteregel-magneet",
      "placeholder": "bijv. \"Stop met scrollen. Lees dit.\"",
      "help": "De exacte eerste regel — Instagram kapt af na ~125 tekens"
    },
    "announcementType": {
      "label": "Type aankondiging",
      "help": "Type interne communicatie"
    },
    "actionRequired": {
      "label": "Actie vereist?",
      "help": "Of medewerkers iets moeten doen"
    },
    "affectedTeams": {
      "label": "Betrokken teams / afdelingen",
      "placeholder": "bijv. Marketing, Sales, Product, Alle medewerkers",
      "help": "Voor wie deze communicatie bedoeld is"
    },
    "keyRequirements": {
      "label": "Belangrijkste eisen",
      "placeholder": "bijv. 5+ jaar marketing, B2B-ervaring, datagedreven",
      "help": "Must-have kwalificaties"
    },
    "uniquePerks": {
      "label": "Unieke arbeidsvoorwaarden / voordelen",
      "placeholder": "bijv. 4-daagse werkweek, leerbudget, aandelen",
      "help": "Onderscheidende voordelen om uit te lichten"
    },
    "sectionSkeleton": {
      "label": "Sectieskelet",
      "placeholder": "Eén sectie per regel:\n- Het probleem dat niemand benoemt\n- De data die het bewijst\n- Onze aanpak\n- Bewijs uit een klantcase\n- De volgende stap",
      "help": "Eén sectie per regel — 1-op-1 gebruikt als sectietitel. Optioneel: `Titel — bullet1; bullet2` voor subpunten."
    },
    "sectionHook": {
      "label": "Hook eerste sectie",
      "placeholder": "bijv. \"De meeste merken meten hun brand voice niet — wij wel.\"",
      "help": "Exacte openingsregel voor sectie 1 (of het geheel). Doorslaggevend voor engagement."
    },
    "conversionGoal": {
      "label": "Conversiedoel",
      "help": "Primaire actie die bezoekers moeten nemen"
    },
    "trafficSource": {
      "label": "Primaire verkeersbron",
      "help": "Waar bezoekers vandaan komen beïnvloedt de boodschap"
    },
    "adFormat": {
      "label": "Advertentieformaat",
      "help": "LinkedIn-advertentieplaatsingsformaat — kies voor video-ads het contenttype 'LinkedIn Video Ad'"
    },
    "personalCredentials": {
      "label": "Persoonlijke credentials",
      "placeholder": "bijv. \"15 jaar brand-strategie bij B2B SaaS, ex-VP Brand bij ACME\"",
      "help": "Waarom is deze auteur gekwalificeerd om dit standpunt in te nemen?"
    },
    "authorPerspective": {
      "label": "Auteursperspectief",
      "placeholder": "bijv. VP Marketing die geleerde lessen deelt",
      "help": "Professionele invalshoek en autoriteitspositionering"
    },
    "slideSkeleton": {
      "label": "Slideskelet",
      "placeholder": "Eén slide per regel:\n- Het probleem dat niemand benoemt\n- De data die het bewijst\n- Onze aanpak\n- Bewijs uit een klantcase\n- De volgende stap",
      "help": "Eén slide per regel — 1-op-1 gebruikt als slidetitel. Optioneel: `Titel — bullet1; bullet2` voor subpunten."
    },
    "slideHook": {
      "label": "Hook eerste slide",
      "placeholder": "bijv. \"De meeste merken meten hun brand voice niet — wij wel.\"",
      "help": "Exacte openingsregel voor slide 1 (of het geheel). Doorslaggevend voor engagement."
    },
    "transitionStyle": {
      "label": "Overgangsstijl"
    },
    "includeCtaSlide": {
      "label": "CTA-slide toevoegen",
      "help": "Laatste slide is een dedicated call-to-action"
    },
    "slidesCount": {
      "label": "Aantal slides",
      "placeholder": "bijv. 8",
      "help": "Doelaantal slides/kaarten"
    },
    "narrativeStructure": {
      "label": "Narratieve structuur",
      "help": "Structuur van de slide-flow"
    },
    "eventName": {
      "label": "Evenementnaam",
      "placeholder": "bijv. Brand Strategy Masterclass 2026",
      "help": "Officiële evenementtitel"
    },
    "eventDate": {
      "label": "Datum & tijd evenement",
      "placeholder": "bijv. 15 juni 2026 om 14:00 CET",
      "help": "Datum, tijd en tijdzone"
    },
    "eventUrl": {
      "label": "Registratie-URL",
      "placeholder": "https://…",
      "help": "Link naar registratie- of evenementpagina"
    },
    "eventLocation": {
      "label": "Locatie",
      "placeholder": "bijv. Online (Zoom) of Amsterdam, Nederland",
      "help": "Fysieke locatie of virtueel platform"
    },
    "speakers": {
      "label": "Sprekers / hosts",
      "placeholder": "Sprekernaam toevoegen…",
      "help": "Uitgelichte sprekers of panelleden"
    },
    "ctaPlacement": {
      "label": "CTA-plaatsing"
    },
    "previewTextLength": {
      "label": "Lengte preview-tekst (tekens)",
      "placeholder": "90",
      "help": "Tekens zichtbaar in de preview van de e-mailclient (30–150)"
    },
    "personalize": {
      "label": "Personalisatie",
      "help": "Gebruik naam van ontvanger en dynamische content"
    },
    "subjectLine": {
      "label": "Onderwerpregel",
      "placeholder": "bijv. Jouw merk verdient beter",
      "help": "Onderwerpregel van de e-mail (AI stelt ook alternatieven voor)"
    },
    "newsletterTheme": {
      "label": "Nieuwsbriefthema",
      "placeholder": "bijv. Wekelijkse brand-strategie-inzichten",
      "help": "Terugkerend thema of serienaam"
    },
    "pollQuestion": {
      "label": "Poll-vraag",
      "placeholder": "bijv. Wat is je grootste merkuitdaging?",
      "help": "De vraag die je stelt (max ~140 tekens op LinkedIn)"
    },
    "pollOptions": {
      "label": "Poll-opties",
      "placeholder": "Optie toevoegen…",
      "help": "2-4 antwoordopties"
    },
    "personalAnecdote": {
      "label": "Open met een persoonlijke anekdote",
      "help": "Open met een persoonlijke scène van 1-2 zinnen vóór het argument"
    },
    "hookStrategy": {
      "label": "Hook-strategie (eerste 3s)",
      "help": "Hoe je het scrollen stopt in de eerste 3 seconden (geluidloze autoplay)"
    },
    "captionStyle": {
      "label": "Stijl on-screen ondertiteling",
      "help": "LinkedIn-autoplay is geluidloos — ondertitels zijn essentieel voor kijktijd. Standaard: ingebrand."
    },
    "journalistRecentArticle": {
      "label": "Recent artikel van de journalist (referentie)",
      "placeholder": "bijv. \"Marketing Week 2026-04-12 — 'Brand-tools die nooit pivoteren'\"",
      "help": "Titel of samenvatting van een recent stuk van deze journalist — pitches zonder dit worden automatisch verwijderd"
    },
    "dataPoint": {
      "label": "Hero-datapunt",
      "placeholder": "bijv. \"3 op de 5 B2B-merken meten hun brand voice niet\"",
      "help": "1 verrassend cijfer / getal dat de pitch verankert"
    },
    "targetJournalist": {
      "label": "Doel-journalist / -publicatie",
      "placeholder": "bijv. Marketing Week, Adformatie, specifieke journalistnaam",
      "help": "Aan wie je pitcht"
    },
    "exclusiveAngle": {
      "label": "Exclusieve invalshoek",
      "placeholder": "bijv. Eerste blik op AI-brand-strategie-tool met exclusieve data",
      "help": "Wat deze pitch nieuwswaardig maakt voor deze journalist"
    },
    "editorialPretext": {
      "label": "Redactionele aanleiding",
      "placeholder": "bijv. \"3 lessen die brand-managers leerden over consistentie\"",
      "help": "Redactionele framing — wat het als content laat lezen, niet als advertentie"
    },
    "publisherStyle": {
      "label": "Uitgever- / redactiestijl",
      "placeholder": "bijv. Sluit aan bij de redactionele toon van TechCrunch",
      "help": "Native ads moeten aansluiten bij de stijl van het gastmedium"
    },
    "emailCount": {
      "label": "Aantal e-mails",
      "placeholder": "bijv. 5",
      "help": "E-mails in de nurture-reeks"
    },
    "buyingStage": {
      "label": "Instap-koopfase",
      "help": "Waar leads deze reeks binnenkomen"
    },
    "keyObjections": {
      "label": "Bezwaren om te adresseren",
      "placeholder": "bijv. Prijs te hoog, Twijfel over ROI",
      "help": "Veelvoorkomende bezwaren om in de reeks te weerleggen"
    },
    "salesAngle": {
      "label": "Verkoop-invalshoek"
    },
    "includePricing": {
      "label": "Prijssectie toevoegen",
      "help": "Alleen placeholder — laat weg als de prijs maatwerk is"
    },
    "subTopicMap": {
      "label": "Subonderwerp-map (3-7 H2's)",
      "placeholder": "Eén subonderwerp per regel — wordt een H2:\n- Hoe brand voice operationeel te definiëren\n- Waarom de meeste voice-guides falen\n- Voice-fidelity meten",
      "help": "3-7 subonderwerpen — deze worden H2-secties + sturen de interne-linkstrategie"
    },
    "internalSubpages": {
      "label": "Interne subpagina's om te linken (optioneel)",
      "placeholder": "Eén URL of paginatitel per regel",
      "help": "Bestaande subpagina's om vanuit deze pillar te cross-linken (optioneel)"
    },
    "agendaSkeleton": {
      "label": "Agendapunt-skelet",
      "placeholder": "Eén agendapunt per regel:\n- Het probleem dat niemand benoemt\n- De data die het bewijst\n- Onze aanpak\n- Bewijs uit een klantcase\n- De volgende stap",
      "help": "Eén agendapunt per regel — 1-op-1 gebruikt als agendapunttitel. Optioneel: `Titel — bullet1; bullet2` voor subpunten."
    },
    "agendaHook": {
      "label": "Openingshook",
      "placeholder": "bijv. \"De meeste merken meten hun brand voice niet — wij wel.\"",
      "help": "Exacte openingsregel voor agendapunt 1 (of het geheel). Doorslaggevend voor engagement."
    },
    "centralQuestion": {
      "label": "Centrale vraag",
      "placeholder": "bijv. \"Waarom faalt merkconsistentie bij bureaus maar slaagt ze in-house?\"",
      "help": "De ene vraag die de aflevering onderzoekt — houdt het gesprek gefocust"
    },
    "episodeFormat": {
      "label": "Afleveringsformaat"
    },
    "segmentCount": {
      "label": "Segmenten (1–8)",
      "placeholder": "3",
      "help": "Aantal aparte segmenten met overgangen"
    },
    "introStyle": {
      "label": "Introstijl"
    },
    "includeShowNotes": {
      "label": "Shownotes genereren"
    },
    "includeTranscript": {
      "label": "Transcript genereren"
    },
    "guestInfo": {
      "label": "Naam & bio gast",
      "placeholder": "bijv. Jane Doe, CEO van BrandCo — 15 jaar in brand-strategie",
      "help": "Gastdetails voor interview-achtige afleveringen"
    },
    "newsFact": {
      "label": "Nieuwsfeit / aankondiging",
      "placeholder": "bijv. Lancering van nieuw AI-gedreven merkanalyseplatform",
      "help": "Het nieuwswaardige feit of de aankondiging"
    },
    "releaseDate": {
      "label": "Publicatiedatum",
      "placeholder": "bijv. 15 juni 2026",
      "help": "Publicatiedatum (voor de dateline)"
    },
    "spokespersonQuote": {
      "label": "Quote woordvoerder",
      "placeholder": "bijv. 'Deze lancering betekent...' — CEO-naam",
      "help": "Quote van een bedrijfsleider"
    },
    "contactInfo": {
      "label": "Perscontact",
      "placeholder": "bijv. press@bedrijf.com, +31 20 123 4567",
      "help": "Contactinformatie voor media"
    },
    "productSpecs": {
      "label": "Productspecificaties",
      "placeholder": "Technische specs, afmetingen, materialen, enz.",
      "help": "Belangrijke productdetails om op te nemen"
    },
    "pricingInfo": {
      "label": "Prijs",
      "placeholder": "bijv. €99, vanaf €49/maand",
      "help": "Productprijs om te vermelden"
    },
    "productId": {
      "label": "Gekoppeld product",
      "help": "Het product/de dienst uit je kennissectie waar deze pagina over gaat"
    },
    "featureBenefitMap": {
      "label": "Functie → voordeel-map",
      "placeholder": "Eén paar per regel — functie → voordeel:\n- Voice-fidelity-scoring → weet dat je copy on-brand is vóór publicatie\n- Templatebibliotheek → 80% minder reviewrondes",
      "help": "Eén functie → voordeel-paar per regel. Voorkomt dat productpagina's een opsomming van functies worden."
    },
    "musicDirection": {
      "label": "Muziek- / geluidsrichting",
      "placeholder": "bijv. Upbeat electronic, corporate ambient, akoestisch",
      "help": "Sturing voor sfeer en stijl van de muziek"
    },
    "urgencyMechanism": {
      "label": "Urgentiemechanisme",
      "help": "Promo-mails zonder urgentiemechanisme lezen als 'leuk om te weten'"
    },
    "socialProofSnippet": {
      "label": "Social-proof-snippet (optioneel)",
      "placeholder": "bijv. \"'3x sneller dan onze vorige tool' — Maartje, brand lead bij ACME\"",
      "help": "1 klantquote / cijfer / casefragment dat het aanbod ondersteunt"
    },
    "offerDetails": {
      "label": "Aanbieddetails",
      "placeholder": "bijv. 30% korting op jaarplannen tot 30 juni",
      "help": "Het specifieke aanbod, de korting of de promotie"
    },
    "clientName": {
      "label": "Klant- / projectnaam",
      "placeholder": "bijv. TechCorp Q3 brand refresh",
      "help": "Klantnaam voor personalisatie van het voorstel"
    },
    "projectScope": {
      "label": "Projectscope",
      "placeholder": "bijv. Volledige herontwerp merkidentiteit incl. logo, richtlijnen en collateral",
      "help": "Scope van het werk op hoofdlijnen"
    },
    "budgetRange": {
      "label": "Budgetrange",
      "placeholder": "bijv. €15.000 - €25.000",
      "help": "Budgetindicatie voor het voorstel"
    },
    "timeline": {
      "label": "Projecttijdlijn",
      "placeholder": "bijv. 6 weken, start juli 2026",
      "help": "Verwachte projectduur"
    },
    "lastValueDelivered": {
      "label": "Laatst geleverde waarde",
      "placeholder": "bijv. \"laatst getoonde interesse: brand-voice-analyzer voor LinkedIn\"",
      "help": "Anker — wat de gebruiker de vorige keer concreet interesseerde"
    },
    "pivotAngle": {
      "label": "Pivot-invalshoek",
      "placeholder": "bijv. \"vraag of de pijn nog relevant is, niet 'we missen je'\"",
      "help": "Hoe de e-mail wegdraait van het generieke 'we missen je'"
    },
    "incentive": {
      "label": "Re-engagement-incentive",
      "placeholder": "bijv. 20% welkom-terug-korting, exclusieve content",
      "help": "Wat terugkomst motiveert (korting, exclusiviteit, herinnering)"
    },
    "inactivityPeriod": {
      "label": "Inactiviteitsperiode",
      "help": "Hoe lang de abonnee al inactief is"
    },
    "previousActionContext": {
      "label": "Context vorige actie",
      "placeholder": "bijv. \"bekeek prijspagina 3 dagen geleden, haakte af vóór aanmelding\"",
      "help": "Wat de gebruiker concreet deed — copy moet hier direct naar verwijzen"
    },
    "incentiveOffer": {
      "label": "Incentive-aanbod (optioneel)",
      "placeholder": "bijv. \"15% korting als je je deze week aanmeldt\"",
      "help": "Optionele incentive om de reden van afhaken te overwinnen"
    },
    "retargetingSegment": {
      "label": "Retargeting-segment",
      "help": "Welk doelgroepsegment wordt geretarget"
    },
    "productReference": {
      "label": "Product / pagina om naar te verwijzen",
      "placeholder": "bijv. Product X dat ze bekeken, prijspagina",
      "help": "Waarmee de gebruiker eerder interacteerde"
    },
    "centralPainPoint": {
      "label": "Centrale pijn",
      "placeholder": "bijv. \"Inconsistentie kost teams 30% meer review-tijd\"",
      "help": "De ene pijn waar het hele stuk op ankert (ruggengraat deck/one-pager)"
    },
    "competitorContext": {
      "label": "Concurrentcontext",
      "placeholder": "bijv. \"vs. legacy tools die brand voice nog handmatig reviewen\"",
      "help": "Hoe de deck zich positioneert t.o.v. concurrenten (1 zin)"
    },
    "targetKeywords": {
      "label": "Doelzoekwoorden",
      "placeholder": "Zoekwoord toevoegen…",
      "help": "Zoekwoorden waarop deze advertentie target in Google/Bing"
    },
    "adPlatform": {
      "label": "Platform",
      "help": "Het social-ad-platform bepaalt formaat en copy-beperkingen"
    },
    "adObjective": {
      "label": "Advertentiedoel",
      "help": "Advertentiedoel-instelling van het platform"
    },
    "platform": {
      "label": "Platform",
      "help": "Platform bepaalt formaatbeperkingen en toon"
    },
    "keyMessages": {
      "label": "Belangrijkste boodschappen om vast te leggen",
      "placeholder": "bijv. Tijdsbesparing, behaalde ROI, teamadoptie",
      "help": "Kernpunten die de testimonial moet overbrengen"
    },
    "industryNorm": {
      "label": "Branchenorm (de consensus die je uitdaagt)",
      "placeholder": "bijv. \"De meeste brand-consultants behandelen brand voice als smaak — subjectief, ontestbaar\"",
      "help": "Wat iedereen in dit veld nu gelooft — en wat jij op het punt staat uit te dagen"
    },
    "trendReference": {
      "label": "Trend- / geluidsreferentie",
      "placeholder": "bijv. 'Day in the life'-format, trending audio XYZ",
      "help": "TikTok-trend of -geluid om te benutten"
    },
    "threadLength": {
      "label": "Threadlengte (tweets)",
      "placeholder": "bijv. 7",
      "help": "Aantal tweets in de thread (5-15 aanbevolen)"
    },
    "openingHook": {
      "label": "Openingstweet — exacte tekst",
      "placeholder": "bijv. \"De meeste B2B-merken denken dat consistentie ze afremt. Het tegenovergestelde is waar.\"",
      "help": "De letterlijke eerste tweet (max 280 tekens) — doorslaggevend voor thread-engagement"
    },
    "tweetSkeleton": {
      "label": "Tweet-skelet (optioneel)",
      "placeholder": "Eén tweet per regel — outline van de thread",
      "help": "Optioneel: schets tweet voor tweet (één per regel) om de structuur vast te zetten"
    },
    "hookSecond": {
      "label": "0:00 – 0:03 — visuele hook",
      "placeholder": "bijv. \"Close-up van handen die een notitieboek dichtslaan\"",
      "help": "Wat er in de eerste 3 seconden gebeurt — doorslaggevend voor skip-gedrag"
    },
    "payoffMoment": {
      "label": "Payoff-moment (tijdstip + scène)",
      "placeholder": "bijv. \"0:18 — split-screen: chaotische marketing vs. consistent merk\"",
      "help": "Scène waar de waarde bij de kijker landt"
    },
    "skipDeterrent": {
      "label": "Skip-drempel (0:00 – 0:05)",
      "placeholder": "bijv. \"open met een uitspraak die de exacte frustratie van de kijker benoemt\"",
      "help": "Specifieke tactiek om skip te voorkomen in het 5-seconden-skipvenster"
    },
    "targetTakeaway": {
      "label": "Doel-takeaway",
      "placeholder": "bijv. \"Een meetbare brand voice is een operationele keuze, geen creatieve\"",
      "help": "1 zin die de doelgroep moet onthouden na het bekijken van dit stuk"
    },
    "webinarFormat": {
      "label": "Webinarformaat",
      "help": "Webinarstructuur"
    },
    "interactionPoints": {
      "label": "Interactiemomenten",
      "placeholder": "bijv. Poll op 10 min, Q&A op 25 min, breakout op 35 min",
      "help": "Geplande momenten voor publieksinteractie"
    },
    "sendInterval": {
      "label": "Verzendinterval",
      "help": "Tijd tussen e-mails in de reeks"
    },
    "onboardingSteps": {
      "label": "Belangrijkste onboarding-stappen",
      "placeholder": "bijv. Profiel instellen, Eerste project, Team uitnodigen",
      "help": "Acties die je nieuwe gebruikers wilt laten voltooien"
    }
  },
  "options": {
    "articleStructure": {
      "deep-dive": "Deep dive — één onderwerp, de diepte in",
      "listicle": "Listicle — genummerde lijst met punten",
      "how-to": "How-to-gids — stap voor stap",
      "explainer": "Explainer — een complex concept ontleden",
      "comparison": "Vergelijking — opties of aanpakken vergelijken",
      "narrative": "Verhalend — verhaalgedreven boog"
    },
    "optimizationGoals": {
      "seo": "SEO-optimalisatie",
      "geo": "GEO-optimalisatie (AI-citeerbaarheid)"
    },
    "structure": {
      "inverted-pyramid": "Omgekeerde piramide — belangrijkste eerst",
      "chronological": "Chronologisch — tijdlijn / verhaalboog",
      "profile": "Profiel — persoonsgericht",
      "impact-report": "Impactrapport — cijfers + verhaal"
    },
    "tonePosition": {
      "factual": "Feitelijk — neutrale vergelijking, laat de data spreken",
      "persuasive": "Overtuigend — beargumenteer actief je zaak",
      "diplomatic": "Diplomatiek — erken eerst hun sterke punten"
    },
    "hookFormat": {
      "pattern-interrupt": "Pattern interrupt — doorbreek het verwachte ritme",
      "question": "Vraag — open met een prikkelende vraag",
      "stat": "Cijfer — verrassend getal eerst",
      "contrarian-take": "Contraire mening — daag een gangbaar geloof uit",
      "story-open": "Verhaalopening — verhalende microscène",
      "listicle-promise": "Listicle-belofte — beloof N items / stappen"
    },
    "ctaType": {
      "learn-more": "Meer informatie",
      "sign-up": "Aanmelden",
      "shop-now": "Shop nu",
      "contact-us": "Neem contact op"
    },
    "storyAngle": {
      "Career Growth": "Carrièregroei",
      "Day in the Life": "Een dag uit het leven",
      "Project Highlight": "Projecthoogtepunt",
      "Culture & Values": "Cultuur & waarden",
      "Innovation Story": "Innovatieverhaal"
    },
    "footageType": {
      "real-person": "Echt persoon",
      "stock": "Stockbeelden",
      "animation": "Animatie",
      "mixed": "Gemengd"
    },
    "textOverlay": {
      "bold-headlines": "Gedurfde koppen",
      "minimal": "Minimaal",
      "dynamic-captions": "Dynamische ondertitels"
    },
    "colorGrade": {
      "warm": "Warm",
      "cool": "Koel",
      "vibrant": "Levendig",
      "natural": "Natuurlijk"
    },
    "videoFormat": {
      "Animation / Motion Graphics": "Animatie / motion graphics",
      "Screen Recording": "Schermopname",
      "Live Action": "Live action",
      "Mixed Media": "Mixed media"
    },
    "complexityLevel": {
      "Simple (consumer)": "Eenvoudig (consument)",
      "Moderate (prosumer)": "Gemiddeld (prosumer)",
      "Complex (technical)": "Complex (technisch)"
    },
    "hashtagStrategy": {
      "trending": "Trending — breed bereik",
      "niche": "Niche — gerichte community",
      "branded": "Branded — eigen hashtags",
      "mixed": "Gemengd — combinatie",
      "none": "Geen"
    },
    "postType": {
      "Link Share": "Link delen",
      "Photo": "Foto",
      "Video": "Video",
      "Event": "Evenement",
      "Status Update": "Statusupdate"
    },
    "audienceMood": {
      "casual-conversational": "Casual / conversationeel — vriendelijk, licht",
      "community-rallying": "Community mobiliseren — appelleert aan gedeelde identiteit",
      "informative-helpful": "Informatief / behulpzaam — uitlegstem",
      "playful-irreverent": "Speels / oneerbiedig — humor, verrassing"
    },
    "stakeholderAudience": {
      "Investors": "Investeerders",
      "Customers": "Klanten",
      "Employees": "Medewerkers",
      "General Public": "Algemeen publiek",
      "Regulators": "Toezichthouders"
    },
    "esgFramework": {
      "GRI": "GRI",
      "SASB": "SASB",
      "TCFD": "TCFD",
      "B Corp": "B Corp",
      "UN SDGs": "UN SDGs",
      "Custom": "Aangepast"
    },
    "captionLength": {
      "short": "Kort — 1 zin + emoji",
      "medium": "Gemiddeld — 3-5 zinnen",
      "long": "Lang — micro-essay (5+ zinnen)"
    },
    "announcementType": {
      "Company Update": "Bedrijfsupdate",
      "Policy Change": "Beleidswijziging",
      "Product Launch": "Productlancering",
      "Leadership Change": "Wisseling in leiderschap",
      "Team Achievement": "Teamprestatie"
    },
    "conversionGoal": {
      "Email Signup": "E-mailaanmelding",
      "Free Trial": "Gratis proefperiode",
      "Download": "Download",
      "Purchase": "Aankoop",
      "Demo Request": "Demo-aanvraag",
      "Contact Form": "Contactformulier"
    },
    "trafficSource": {
      "Paid Ads": "Betaalde advertenties",
      "Email": "E-mail",
      "Organic Search": "Organisch zoeken",
      "Social Media": "Social media",
      "Referral": "Referral"
    },
    "adFormat": {
      "single-image": "Enkele afbeelding",
      "message-ad": "Bericht-advertentie"
    },
    "transitionStyle": {
      "continuous": "Doorlopend — content loopt door over slides",
      "standalone": "Standalone — elke slide onafhankelijk",
      "story-arc": "Verhaalboog — bouwt naar een conclusie"
    },
    "narrativeStructure": {
      "Listicle (tips/steps)": "Listicle (tips/stappen)",
      "Before & After": "Voor & na",
      "Problem → Solution": "Probleem → oplossing",
      "Data Story": "Dataverhaal",
      "How-To Guide": "How-to-gids"
    },
    "ctaPlacement": {
      "above-fold": "Boven de vouw",
      "bottom": "Onderaan",
      "multiple": "Meerdere CTA's",
      "inline": "Inline"
    },
    "hookStrategy": {
      "bold-statement": "Gedurfde uitspraak / contra-intuïtieve claim",
      "question": "Open vraag",
      "pattern-interrupt": "Pattern-interrupt visual",
      "stat-shock": "Verrassende statistiek",
      "story-open": "Verhaalopening midden in de scène"
    },
    "captionStyle": {
      "burned-in": "Ingebrande ondertitels (altijd zichtbaar)",
      "auto-closed": "Automatisch gegenereerde ondertiteling",
      "key-phrases": "Kernzin-overlays (alleen highlights)"
    },
    "buyingStage": {
      "Awareness": "Bewustwording",
      "Consideration": "Overweging",
      "Evaluation": "Evaluatie",
      "Decision": "Beslissing"
    },
    "salesAngle": {
      "problem-solution": "Probleem → oplossing — pijn-gedreven",
      "benefit-led": "Voordeel-gedreven — begin met uitkomsten",
      "feature-focused": "Functie-gericht — capaciteiten uitgesplitst",
      "social-proof": "Social proof — klantsuccessen eerst",
      "competitive": "Competitief — onderscheiden t.o.v. alternatieven"
    },
    "episodeFormat": {
      "solo": "Solo",
      "interview": "Interview",
      "panel": "Panel",
      "narrative": "Verhalend"
    },
    "introStyle": {
      "cold-open": "Cold open — meteen erin",
      "teaser": "Teaser — preview van de kernpunten",
      "music-intro": "Muziekintro — themamuziek + host-intro"
    },
    "urgencyMechanism": {
      "deadline": "Deadline — datum/tijd-gebonden",
      "scarcity": "Schaarste — beperkte voorraad / plekken",
      "loss-aversion": "Verliesaversie — wat ze verliezen door niets te doen",
      "none": "Geen — evergreen / geen kunstmatige urgentie"
    },
    "inactivityPeriod": {
      "30 days": "30 dagen",
      "60 days": "60 dagen",
      "90 days": "90 dagen",
      "6+ months": "6+ maanden"
    },
    "retargetingSegment": {
      "Cart Abandonment": "Verlaten winkelwagen",
      "Page Visitors": "Paginabezoekers",
      "Past Customers": "Oud-klanten",
      "Email Subscribers": "E-mailabonnees",
      "Video Viewers": "Videokijkers"
    },
    "adPlatform": {
      "Facebook": "Facebook",
      "Instagram": "Instagram",
      "LinkedIn": "LinkedIn",
      "TikTok": "TikTok"
    },
    "adObjective": {
      "Traffic": "Verkeer",
      "Conversions": "Conversies",
      "Lead Generation": "Leadgeneratie",
      "Brand Awareness": "Merkbekendheid",
      "Engagement": "Engagement"
    },
    "platform": {
      "Instagram": "Instagram",
      "LinkedIn": "LinkedIn",
      "Facebook": "Facebook"
    },
    "webinarFormat": {
      "Presentation + Q&A": "Presentatie + Q&A",
      "Panel Discussion": "Paneldiscussie",
      "Workshop / Hands-on": "Workshop / hands-on",
      "Interview": "Interview",
      "Demo": "Demo"
    },
    "sendInterval": {
      "Daily": "Dagelijks",
      "Every 2 Days": "Elke 2 dagen",
      "Every 3 Days": "Elke 3 dagen",
      "Weekly": "Wekelijks"
    }
  },
  "byType": {
    "employer-brand-video": {
      "storyAngle": {
        "label": "Videofocus",
        "help": "Verhalende focus van de video",
        "options": {
          "Culture Overview": "Cultuuroverzicht",
          "Employee Testimonials": "Medewerker-testimonials",
          "Office / Workspace Tour": "Kantoor- / werkplekrondleiding",
          "Team Collaboration": "Teamsamenwerking",
          "Impact & Mission": "Impact & missie"
        }
      }
    },
    "job-ad-copy": {
      "jobTitle": {
        "label": "Functietitel",
        "placeholder": "bijv. Marketing Manager",
        "help": "Functietitel"
      }
    },
    "landing-page": {
      "payoffPosition": {
        "label": "Payoff-sectie (nummer)",
        "placeholder": "4",
        "help": "Welk sectienummer levert de payoff (meestal op 60-70% van het geheel)."
      },
      "socialProof": {
        "label": "Beschikbare social proof",
        "placeholder": "bijv. Klantlogo's, testimonials, cijfers",
        "help": "Vertrouwenselementen om op de pagina te tonen"
      }
    },
    "linkedin-article": {
      "seoKeyword": {
        "label": "SEO-zoekwoord",
        "placeholder": "bijv. merkpositioneringsstrategie",
        "help": "Optioneel — helpt de AI de invalshoek te focussen. Laat leeg als je geen doelzoekwoord hebt."
      }
    },
    "linkedin-carousel": {
      "payoffPosition": {
        "label": "Payoff-slide (nummer)",
        "placeholder": "4",
        "help": "Welk slidenummer levert de payoff (meestal op 60-70% van het geheel)."
      }
    },
    "linkedin-post": {
      "postType": {
        "label": "Posttype",
        "help": "Bepaalt structuur en toon",
        "options": {
          "Thought Leadership": "Thought leadership",
          "Company News": "Bedrijfsnieuws",
          "Personal Story": "Persoonlijk verhaal",
          "Industry Insight": "Branche-inzicht",
          "Poll / Question": "Poll / vraag",
          "Case Study Snippet": "Case study-snippet"
        }
      }
    },
    "linkedin-video": {
      "videoFormat": {
        "label": "Videoformaat",
        "help": "Productiestijl",
        "options": {
          "Talking Head": "Talking head",
          "Screen Recording": "Schermopname",
          "Animation": "Animatie",
          "B-Roll Montage": "B-roll-montage"
        }
      }
    },
    "one-pager": {
      "keyMetrics": {
        "label": "Bewijspunten",
        "placeholder": "bijv. 500+ klanten, 99,9% uptime",
        "help": "Kwantificeerbaar waardebewijs"
      }
    },
    "podcast-outline": {
      "payoffPosition": {
        "label": "Payoff-agendapunt (nummer)",
        "placeholder": "4",
        "help": "Welk agendapuntnummer levert de payoff (meestal op 60-70% van het geheel)."
      }
    },
    "product-page": {
      "productSpecs": {
        "label": "Extra productspecs (optioneel)",
        "placeholder": "bijv. Afmetingen, materialen, compatibiliteit, prijs",
        "help": "Aanvullende specs bovenop het gekoppelde product — alleen wat nog niet in het productrecord staat"
      },
      "pricingInfo": {
        "label": "Prijsinformatie",
        "placeholder": "bijv. Vanaf €49/maand, gratis versie beschikbaar",
        "help": "Prijs om te tonen of naar te verwijzen"
      }
    },
    "sales-deck": {
      "payoffPosition": {
        "label": "Payoff-slide (nummer)",
        "placeholder": "4",
        "help": "Welk slidenummer levert de payoff (meestal op 60-70% van het geheel)."
      },
      "pricingInfo": {
        "label": "Prijs / investering",
        "placeholder": "bijv. Vanaf €5K/maand, custom enterprise-prijzen",
        "help": "Prijsinformatie om in de deck op te nemen"
      },
      "keyMetrics": {
        "label": "Bewijspunten / cijfers",
        "placeholder": "bijv. 150+ klanten, 40% gem. ROI-stijging",
        "help": "Kwantificeerbare resultaten en credentials"
      }
    },
    "search-ad": {
      "headlineCount": {
        "label": "Kopvarianten (standaard 3)",
        "placeholder": "3",
        "help": "Aantal kopvariaties om te genereren (best practice Google search-ad-asset: 3-5)"
      }
    },
    "social-carousel": {
      "payoffPosition": {
        "label": "Payoff-slide (nummer)",
        "placeholder": "4",
        "help": "Welk slidenummer levert de payoff (meestal op 60-70% van het geheel)."
      },
      "narrativeStructure": {
        "label": "Slide-narratief",
        "help": "Hoe slides samen een verhaal vormen",
        "options": {
          "Listicle": "Listicle",
          "Before & After": "Voor & na",
          "Problem → Solution": "Probleem → oplossing",
          "Step-by-Step": "Stap voor stap",
          "Data Story": "Dataverhaal"
        }
      }
    },
    "testimonial-video": {
      "customerName": {
        "label": "Uitgelichte klant",
        "placeholder": "bijv. Sarah Chen, VP Marketing bij TechCorp",
        "help": "Naam en functie van de klant voor de testimonial"
      }
    },
    "thought-leadership": {
      "authorPerspective": {
        "label": "Auteurs- / executive-perspectief",
        "placeholder": "bijv. CEO-visie op disruptie in de branche",
        "help": "Wiens perspectief en welke contraire invalshoek"
      }
    },
    "video-ad": {
      "adPlatform": {
        "label": "Platform",
        "help": "Platform bepaalt tempo en skip-gedrag",
        "options": {
          "YouTube Pre-Roll": "YouTube pre-roll",
          "YouTube Bumper (6s)": "YouTube bumper (6s)",
          "Social Feed": "Social feed",
          "Connected TV": "Connected TV"
        }
      }
    },
    "webinar-outline": {
      "payoffPosition": {
        "label": "Payoff-agendapunt (nummer)",
        "placeholder": "4",
        "help": "Welk agendapuntnummer levert de payoff (meestal op 60-70% van het geheel)."
      },
      "speakers": {
        "label": "Sprekers / hosts",
        "placeholder": "Sprekernaam toevoegen…",
        "help": "Namen en functies van presentatoren"
      }
    },
    "welcome-sequence": {
      "emailCount": {
        "label": "Aantal e-mails",
        "placeholder": "bijv. 5",
        "help": "E-mails in de welkomstreeks (3-7 gebruikelijk)"
      }
    }
  }
} as const;

export default ns;
