// Dutch UI strings — `common` namespace. Hand-seeded for Fase 1;
// will be regenerated by the AI translation pipeline.
const common = {
  appearance: {
    title: 'Weergave',
    displayLanguageTitle: 'Weergavetaal',
    displayLanguageHelp:
      'Taal voor menu’s, knoppen en labels in Branddock. Dit verandert niet de taal waarin je content wordt geschreven.',
    scopeOnlyYou: 'Alleen jij',
    saved: 'Weergavetaal bijgewerkt',
    saveFailed: 'Kon de weergavetaal niet bijwerken',
  },
} as const;

export default common;
