// =============================================================
// Brand Brief Emitter (AGENTS.md-style)
//
// Produceert een volledige markdown-brief die een AI coding agent
// (Claude Code, Cursor, Windsurf, Copilot, Aider) direct kan lezen
// als project-context. Bedoeld om in de repo-root als
// `BRAND.md` / `AGENTS.md` / `.cursorrules` te droppen.
//
// In tegenstelling tot DESIGN.md bevat dit GEEN YAML-tokens — alles
// is prose. Voor de tokens zelf verwijst de brief naar de
// bijbehorende DESIGN.md / tokens.json.
//
// Scope: maximum (user keuze 4) — alle 12 brand assets + personas +
// competitors + voice/tone + imagery + iconography + do's/don'ts.
// =============================================================

import type { DesignSystemModel } from '../canonical';

export function emitBrandBrief(model: DesignSystemModel): string {
  const parts: string[] = [];
  parts.push(renderHeader(model));
  parts.push(renderOverview(model));
  parts.push(renderBrandFoundation(model));
  parts.push(renderPersonas(model));
  parts.push(renderCompetitors(model));
  parts.push(renderVoice(model));
  parts.push(renderImagery(model));
  parts.push(renderIconography(model));
  parts.push(renderTokensPointer(model));
  parts.push(renderDosDonts(model));
  return parts.filter((s) => s.length > 0).join('\n') + '\n';
}

// ─── Sections ─────────────────────────────────────────

function renderHeader(model: DesignSystemModel): string {
  const lines: string[] = [];
  lines.push(`# ${model.meta.name} — Brand Brief`);
  lines.push('');
  lines.push(
    `> Persistent brand context for AI coding / design agents.`,
  );
  lines.push(
    `> Place this file in the repository root as \`BRAND.md\` or reference from \`AGENTS.md\`.`,
  );
  lines.push(`> Generated by Branddock on ${new Date(model.meta.generatedAt).toISOString().slice(0, 10)}.`);
  lines.push('');
  return lines.join('\n');
}

function renderOverview(model: DesignSystemModel): string {
  if (!model.prose.overview) return '';
  return `## Overview\n\n${model.prose.overview}\n`;
}

function renderBrandFoundation(model: DesignSystemModel): string {
  const bf = model.extensions.brandFoundation;
  if (!bf || bf.assets.length === 0) return '';
  const lines: string[] = ['## Brand Foundation', ''];
  lines.push('The brand foundation captures strategy, positioning, personality, and promise. Anything an agent produces — copy, design, campaign — must be consistent with these:');
  lines.push('');
  for (const asset of bf.assets) {
    const label = asset.frameworkType ? `${asset.name} (${asset.frameworkType})` : asset.name;
    lines.push(`### ${label}`);
    lines.push('');
    lines.push(asset.summary || '_No narrative captured yet — define this asset in Branddock to enrich this brief._');
    lines.push('');
  }
  return lines.join('\n');
}

function renderPersonas(model: DesignSystemModel): string {
  const personas = model.extensions.brandFoundation?.personas ?? [];
  if (personas.length === 0) return '';
  const lines: string[] = ['## Target Personas', ''];
  lines.push('Speak to these people. Anything that sounds like "general marketing" is wrong.');
  lines.push('');
  for (const p of personas) {
    lines.push(`### ${p.name}${p.tagline ? ` — ${p.tagline}` : ''}`);
    lines.push('');
    if (p.keyTraits.length > 0) {
      lines.push(`- **Key traits:** ${p.keyTraits.join(', ')}`);
    }
    if (p.primaryGoal) {
      lines.push(`- **Primary goal:** ${p.primaryGoal}`);
    }
    if (p.quote) {
      lines.push(`- **In their words:** "${p.quote}"`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

function renderCompetitors(model: DesignSystemModel): string {
  const competitors = model.extensions.brandFoundation?.competitors ?? [];
  if (competitors.length === 0) return '';
  const lines: string[] = ['## Competitive Landscape', ''];
  lines.push('Agents should avoid producing work that could be mistaken for these competitors.');
  lines.push('');
  for (const c of competitors) {
    lines.push(`- **${c.name} (${c.tier}):** ${c.positioning ?? 'no positioning captured'}`);
    if (c.differentiators.length > 0) {
      lines.push(`  - Their differentiators: ${c.differentiators.slice(0, 3).join('; ')}`);
    }
  }
  lines.push('');
  return lines.join('\n');
}

function renderVoice(model: DesignSystemModel): string {
  const v = model.extensions.voice;
  if (!v) return '';
  const lines: string[] = ['## Brand Voice & Tone', ''];
  if (v.principles.length > 0) {
    lines.push('**Principles**');
    for (const p of v.principles) lines.push(`- ${p}`);
    lines.push('');
  }
  if (v.writingGuidelines.length > 0) {
    lines.push('**Writing guidelines**');
    for (const g of v.writingGuidelines) lines.push(`- ${g}`);
    lines.push('');
  }
  if (v.doSayPhrases.length > 0 || v.dontSayPhrases.length > 0) {
    lines.push('**Phrase examples**');
    for (const p of v.doSayPhrases) lines.push(`- ✅ Do say: "${p}"`);
    for (const p of v.dontSayPhrases) lines.push(`- ❌ Don't say: "${p}"`);
    lines.push('');
  }
  return lines.join('\n');
}

function renderImagery(model: DesignSystemModel): string {
  const i = model.extensions.imagery;
  if (!i) return '';
  const lines: string[] = ['## Imagery', ''];
  if (i.photographyStyle) lines.push(`**Mood:** ${i.photographyStyle}`);
  if (i.photographyGuidelines.length > 0) {
    lines.push('');
    lines.push('**Photography guidelines**');
    for (const g of i.photographyGuidelines) lines.push(`- ${g}`);
  }
  if (i.illustrationGuidelines.length > 0) {
    lines.push('');
    lines.push('**Illustration guidelines**');
    for (const g of i.illustrationGuidelines) lines.push(`- ${g}`);
  }
  if (i.donts.length > 0) {
    lines.push('');
    lines.push("**Don'ts**");
    for (const d of i.donts) lines.push(`- ${d}`);
  }
  lines.push('');
  return lines.join('\n');
}

function renderIconography(model: DesignSystemModel): string {
  const i = model.extensions.iconography;
  if (!i) return '';
  const lines: string[] = ['## Iconography', ''];
  if (i.style) lines.push(`- Style: ${i.style}`);
  if (i.strokeWeight) lines.push(`- Stroke weight: ${i.strokeWeight}`);
  if (i.cornerRadius) lines.push(`- Corner radius: ${i.cornerRadius}`);
  if (i.sizing) lines.push(`- Sizing: ${i.sizing}`);
  if (i.colorUsage) lines.push(`- Colour usage: ${i.colorUsage}`);
  lines.push('');
  return lines.join('\n');
}

function renderTokensPointer(model: DesignSystemModel): string {
  const lines: string[] = ['## Design Tokens', ''];
  lines.push(
    `Visual-system tokens (colors, typography scale, rounded, spacing, elevation, component variants) are emitted separately:`,
  );
  lines.push('');
  lines.push(`- **DESIGN.md** — human-readable Stitch format with YAML frontmatter`);
  lines.push(`- **tokens.json** — W3C Design Tokens (DTCG) for Figma / Style Dictionary`);
  lines.push(`- **tailwind.theme.json** — drop-in Tailwind theme fragment`);
  lines.push('');
  lines.push(`Semantic color roles available: ${Object.keys(model.colors).join(', ') || '_none resolved_'}`);
  lines.push(`Typography roles available: ${Object.keys(model.typography).join(', ') || '_none resolved_'}`);
  lines.push('');
  return lines.join('\n');
}

function renderDosDonts(model: DesignSystemModel): string {
  const items = model.prose.dosDonts ?? [];
  if (items.length === 0) return '';
  const lines: string[] = ["## Do's and Don'ts", ''];
  for (const i of items) lines.push(`- ${i}`);
  lines.push('');
  return lines.join('\n');
}
