// =============================================================
// DTCG Emitter — W3C Design Tokens Community Group
//
// Produceert een tokens.json in het W3C Design Tokens Community Group
// format. Consumenten: Figma, Style Dictionary, Supernova, Tokens Studio.
//
// Spec: https://tr.designtokens.org/format/ (editor's draft 8, 2025)
// Core shape: { "$value": ..., "$type": "color|dimension|fontFamily|...",
//               "$description": "..." }
// Groups: nested objects zonder $-prefix (e.g. "colors.primary.$value").
// References: `"{group.name}"` strings.
// =============================================================

import type { DesignSystemModel } from '../canonical';
import { roundedScaleKeys, spacingScaleKeys, elevationLevelKeys } from '../canonical';

interface DtcgToken {
  $value: unknown;
  $type: string;
  $description?: string;
}

interface DtcgGroup {
  [key: string]: DtcgToken | DtcgGroup;
}

export function emitDtcg(model: DesignSystemModel): {
  $description: string;
  colors: DtcgGroup;
  typography: DtcgGroup;
  rounded: DtcgGroup;
  spacing: DtcgGroup;
  elevation: DtcgGroup;
  components: DtcgGroup;
} {
  return {
    $description: `Design tokens for ${model.meta.name}. Generated by Branddock ${model.meta.generatedAt}.`,
    colors: buildColorGroup(model),
    typography: buildTypographyGroup(model),
    rounded: buildDimensionGroup(model.rounded, roundedScaleKeys()),
    spacing: buildDimensionGroup(model.spacing, spacingScaleKeys()),
    elevation: buildElevationGroup(model),
    components: buildComponentGroup(model),
  };
}

function buildColorGroup(model: DesignSystemModel): DtcgGroup {
  const group: DtcgGroup = {};
  for (const [role, tok] of Object.entries(model.colors)) {
    if (!tok) continue;
    group[role] = {
      $value: tok.value,
      $type: 'color',
      $description: tok.source ? `Source: ${tok.source}` : undefined,
    };
  }
  return group;
}

function buildTypographyGroup(model: DesignSystemModel): DtcgGroup {
  const group: DtcgGroup = {};
  for (const [role, tok] of Object.entries(model.typography)) {
    if (!tok) continue;
    // Composite typography token per DTCG spec
    group[role] = {
      $type: 'typography',
      $value: {
        fontFamily: tok.fontFamily,
        fontSize: tok.fontSize,
        fontWeight: tok.fontWeight,
        lineHeight: tok.lineHeight,
        ...(tok.letterSpacing ? { letterSpacing: tok.letterSpacing } : {}),
      },
    };
  }
  return group;
}

function buildDimensionGroup<K extends string>(
  scale: Partial<Record<K, { value: number }>>,
  orderedKeys: K[],
): DtcgGroup {
  const group: DtcgGroup = {};
  for (const key of orderedKeys) {
    const tok = scale[key];
    if (!tok) continue;
    group[key] = {
      $value: `${tok.value}px`,
      $type: 'dimension',
    };
  }
  return group;
}

function buildElevationGroup(model: DesignSystemModel): DtcgGroup {
  const group: DtcgGroup = {};
  for (const level of elevationLevelKeys()) {
    const tok = model.elevation[level];
    if (!tok) continue;
    group[level] = {
      $value: tok.value,
      $type: 'shadow',
    };
  }
  return group;
}

function buildComponentGroup(model: DesignSystemModel): DtcgGroup {
  const group: DtcgGroup = {};
  for (const [variant, tok] of Object.entries(model.components)) {
    const sub: DtcgGroup = {};
    for (const [propKey, propValue] of Object.entries(tok.props)) {
      sub[propKey] = {
        $value: transformTokenRef(propValue),
        $type: inferPropType(propKey),
      };
    }
    group[variant] = sub;
  }
  return group;
}

/**
 * Vertaalt DESIGN.md's `{colors.primary}` token-reference notatie naar de
 * W3C DTCG `{colors.primary}` notatie. Die zijn identiek — dus pass-through.
 * Raw hex/px waarden blijven ongewijzigd.
 */
function transformTokenRef(value: string): string {
  return value;
}

function inferPropType(propKey: string): string {
  if (propKey.toLowerCase().includes('color')) return 'color';
  if (['rounded', 'padding', 'size', 'height', 'width'].includes(propKey)) return 'dimension';
  if (propKey === 'typography') return 'typography';
  return 'string';
}
