// =============================================================
// shadcn CSS Variables Emitter
//
// Produceert een globals.css :root block dat direct in een shadcn/ui
// project gedropt kan worden. v0, Claude Design en Lovable genereren
// meestal shadcn-compatible output; deze export sluit aan op hun
// CSS-variabelen conventie (HSL-triplet per token).
//
// Output shape:
//   :root {
//     --primary: 180 72% 30%;
//     --primary-foreground: 0 0% 100%;
//     ...
//     --radius: 8px;
//   }
//   .dark {
//     /* same variable names, dark-mode values */
//   }
//
// We emitten HSL-triplets (zonder hsl() wrapper) omdat shadcn/ui's
// Tailwind config dat consumeert via `hsl(var(--primary))`.
// =============================================================

import type { DesignSystemModel, SemanticColorRole } from '../canonical';
import { hexToHsl } from '@/features/brandstyle/utils/color-utils';

// Mapping semantic role → shadcn CSS variable name.
// Shadcn gebruikt de `--foreground` suffix voor on-colors i.p.v. `on-*`.
const SHADCN_ALIASES: Partial<Record<SemanticColorRole, string>> = {
  'primary': 'primary',
  'on-primary': 'primary-foreground',
  'primary-container': 'primary-muted',
  'secondary': 'secondary',
  'on-secondary': 'secondary-foreground',
  'tertiary': 'accent',              // shadcn gebruikt "accent" als derde kleur
  'on-tertiary': 'accent-foreground',
  'surface': 'background',
  'on-surface': 'foreground',
  'surface-variant': 'muted',
  'outline': 'border',
  'error': 'destructive',
  'on-error': 'destructive-foreground',
  'success': 'success',
  'warning': 'warning',
  'info': 'info',
};

export function emitShadcnCss(model: DesignSystemModel): string {
  const lines: string[] = [];
  lines.push(`/* Generated by Branddock — ${model.meta.name} */`);
  lines.push('');
  lines.push('@layer base {');
  lines.push('  :root {');
  for (const [role, tok] of Object.entries(model.colors)) {
    if (!tok) continue;
    const varName = SHADCN_ALIASES[role as SemanticColorRole];
    if (!varName) continue;
    const hsl = hexToHslTriplet(tok.value);
    lines.push(`    --${varName}: ${hsl};`);
  }

  // Radius: shadcn verwacht een `--radius` basis (meestal `md`).
  const baseRadius = model.rounded.md?.value ?? model.rounded.sm?.value;
  if (typeof baseRadius === 'number') {
    lines.push(`    --radius: ${baseRadius}px;`);
  }

  // Card/input conventies uit shadcn mappen we op surface-variant / outline
  // als die niet al door een specifiekere alias zijn gedekt.
  if (model.colors['surface-variant']) {
    const hsl = hexToHslTriplet(model.colors['surface-variant'].value);
    lines.push(`    --card: ${hsl};`);
    lines.push(`    --popover: ${hsl};`);
  }
  if (model.colors['on-surface']) {
    const hsl = hexToHslTriplet(model.colors['on-surface'].value);
    lines.push(`    --card-foreground: ${hsl};`);
    lines.push(`    --popover-foreground: ${hsl};`);
  }
  if (model.colors.outline) {
    const hsl = hexToHslTriplet(model.colors.outline.value);
    lines.push(`    --input: ${hsl};`);
    lines.push(`    --ring: ${hsl};`);
  }

  lines.push('  }');
  lines.push('');
  lines.push('  /* Dark mode — uncomment and adjust values once a dark-mode palette is resolved.');
  lines.push('     Branddock currently produces single-mode tokens; dark-mode requires a second');
  lines.push('     analyzer pass against a dark variant of the site (or manual overrides via');
  lines.push('     the System Roles UI). */');
  lines.push('  /*');
  lines.push('  .dark {');
  for (const role of Object.keys(model.colors)) {
    const varName = SHADCN_ALIASES[role as SemanticColorRole];
    if (!varName) continue;
    lines.push(`    --${varName}: 0 0% 0%;`);
  }
  lines.push('  }');
  lines.push('  */');
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

function hexToHslTriplet(hex: string): string {
  const hsl = hexToHsl(hex);
  if (!hsl) return '0 0% 0%';
  return `${hsl.h} ${hsl.s}% ${hsl.l}%`;
}
