"use client";

import { useMemo } from "react";
import { Mic2, Sparkles, Wand2 } from "lucide-react";
import { Button, Badge } from "@/components/shared";
import type { BrandVoiceguide } from "../types/voiceguide.types";

interface VoiceguideHeaderProps {
  voiceguide: BrandVoiceguide;
  onAnalyze?: () => void;
}

/**
 * Page-header for the voiceguide. Shows source badge, savedForAi count,
 * centroid status pill, and a CTA to launch the analyzer.
 */
export function VoiceguideHeader({ voiceguide, onAnalyze }: VoiceguideHeaderProps) {
  const savedCount = useMemo(() => {
    let n = 0;
    if (voiceguide.voiceDnaSavedForAi) n++;
    if (voiceguide.vocabularySavedForAi) n++;
    if (voiceguide.channelTonesSavedForAi) n++;
    if (voiceguide.antiPatternsSavedForAi) n++;
    if (voiceguide.referencesSavedForAi) n++;
    return n;
  }, [voiceguide]);

  const centroidLabel = useMemo(() => {
    if (!voiceguide.centroidComputedAt) return "Centroid: not computed";
    const sampleCount = voiceguide.writingSamples.length;
    const date = new Date(voiceguide.centroidComputedAt);
    const days = Math.floor((Date.now() - date.getTime()) / (1000 * 60 * 60 * 24));
    const ago = days === 0 ? "today" : days === 1 ? "1 day ago" : `${days} days ago`;
    return `Centroid: ${sampleCount} samples · ${ago}`;
  }, [voiceguide.centroidComputedAt, voiceguide.writingSamples.length]);

  const sourceLabel = voiceguide.source === "extracted"
    ? "Migrated from Brand Personality"
    : voiceguide.source === "analyzer"
      ? "Generated by analyzer"
      : "Manual";

  return (
    <div className="bg-white border border-gray-200 rounded-lg px-6 py-4 mb-6">
      <div className="flex items-start justify-between gap-4">
        <div className="flex items-start gap-3">
          <div className="w-10 h-10 rounded-lg bg-teal-50 flex items-center justify-center">
            <Mic2 className="w-5 h-5 text-teal-600" />
          </div>
          <div>
            <h1 className="text-xl font-semibold text-gray-900">Brand Voice</h1>
            <p className="text-sm text-gray-500 mt-0.5">
              Verbal identity — tone, vocabulary, channel-tones, writing samples
            </p>
            <div className="flex items-center gap-2 mt-2">
              <Badge variant="default" className="text-xs">{sourceLabel}</Badge>
              <Badge variant="success" icon={Sparkles} className="text-xs">
                {savedCount}/5 saved for AI
              </Badge>
              <Badge variant="info" className="text-xs">{centroidLabel}</Badge>
            </div>
          </div>
        </div>
        {onAnalyze && (
          <Button variant="primary" size="sm" onClick={onAnalyze}>
            <Wand2 className="w-3.5 h-3.5 mr-1.5" />
            Analyze website
          </Button>
        )}
      </div>
    </div>
  );
}
